services:
  - type: web
    name: hagiang-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://htxtruonghai.com
      - key: PUBLIC_API_URL
        value: https://hagiang-backend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: ADMIN_USERNAME
        value: haihg
      - key: ADMIN_DISPLAY_NAME
        value: Admin
      - key: ADMIN_PASSWORD
        sync: false
