import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)

export const translations = {
    vi: {
        // ── Navigation
        nav_home: '🏠 Trang Chủ',
        nav_blog: '📝 Blog',
        nav_contact: '📞 Liên Hệ',
        btn_login: 'Đăng Nhập',
        btn_logout: 'Thoát',

        // ── Tours Hero
        tours_hero_title: '🗺️ Tour Du Lịch Hà Giang',
        tours_hero_sub: 'Ruộng bậc thang · Đỉnh Mã Pí Lèng · Bình nguyên đá Đồng Văn',
        tours_search: 'Tìm kiếm tour...',
        tours_add: '+ Thêm Tour',
        tours_no_result: 'Không tìm thấy tour nào 😢',
        tours_filter_all: 'Tất cả',
        tours_filter_budget: '💰 Tiết kiệm',
        tours_filter_premium: '⭐ Cao cấp',
        tours_filter_trek: '🥾 Trekking',
        tours_sort: 'Sắp xếp',
        tours_sort_default: 'Mặc định',
        tours_sort_price_asc: 'Giá tăng dần',
        tours_sort_price_desc: 'Giá giảm dần',
        tours_sort_rating: 'Đánh giá cao',
        tours_results: 'tour',

        // ── Tour Card
        card_from: 'Từ',
        card_per_person: '/người',
        card_duration: 'Thời gian',
        card_max: 'Tối đa',
        card_people: 'người',
        card_rating: 'Đánh giá',
        card_detail: 'Chi Tiết',
        card_book: '🗓 Đặt Ngay',
        card_includes: 'Bao gồm:',

        // ── Includes labels
        inc_transport: '🚌 Xe đưa đón',
        inc_meal: '🍽️ Ăn uống',
        inc_guide: '🧭 HDV',
        inc_hotel: '🏨 Lưu trú',
        inc_ticket: '🎫 Vé tham quan',

        // ── Booking Modal
        book_title: '🗺️ Đặt Tour',
        book_step1: 'Chọn ngày',
        book_step2: 'Thông tin',
        book_step3: 'Xác nhận',
        book_departure_date: 'Ngày khởi hành *',
        book_guest_count: 'Số lượng khách',
        book_adults: 'Người lớn',
        book_children: 'Trẻ em',
        book_next: 'Tiếp theo →',
        book_full_name: 'Họ và tên *',
        book_phone: 'Số điện thoại *',
        book_email: 'Email (tùy chọn)',
        book_notes: 'Yêu cầu đặc biệt',
        book_notes_ph: 'Dị ứng thức ăn, phòng riêng, yêu cầu đặc biệt...',
        book_back: '← Quay lại',
        book_summary_title: '📋 Tóm tắt đặt tour',
        book_tour_label: 'Tour',
        book_date_label: 'Ngày khởi hành',
        book_total_guests: 'Tổng khách',
        book_price_per: 'Giá / người',
        book_contact_label: 'Liên hệ',
        book_note_label: 'Ghi chú',
        book_confirm: '✅ Xác Nhận Đặt Tour',
        book_call: '📞 Gọi Ngay 0385.737.705',
        book_no_date: '⚠️ Vui lòng chọn ngày khởi hành',
        book_required_msg: '⚠️ Vui lòng điền đầy đủ thông tin bắt buộc',
        book_success_msg: 'Đặt tour "{title}" thành công! Admin/Mod sẽ liên hệ sớm.',
        book_adults_label: 'người lớn',
        book_children_label: 'trẻ em',
        book_and: 'và',
        book_deleted: 'Đã xoá!',

        // ── Home Page
        hero_badge: '📝 Blog & Chia Sẻ',
        hero_h1_blog: 'Blog Chia Sẻ Của',
        hero_blog_name: 'HTM Trường Hải',
        hero_sub: 'Chia sẻ kinh nghiệm, câu chuyện và những điều thú vị mỗi ngày.',
        hero_btn_blog: '📝 Đọc Blog',
        hero_btn_contact: '📞 Liên Hệ',
        home_recent_posts: 'Bài Viết Mới Nhất',
        home_see_all: 'Xem tất cả',
        cta_title: 'Liên Hệ Với Chúng Tôi',
        cta_sub: 'Có câu hỏi hoặc muốn hợp tác? Liên hệ ngay với HTM Trường Hải',
        cta_call: '📞 Gọi 0385.737.705',
        cta_consult: '📋 Gửi Yêu Cầu',
        logo_sub: 'Blog & Chia Sẻ',

        // ── Blog Page
        blog_hero_title: '📝 Blog & Tin Tức',
        blog_hero_sub: 'Kinh nghiệm du lịch, hướng dẫn order Taobao, khám phá vùng cao',
        blog_search: 'Tìm bài viết...',
        blog_add: 'Đăng Bài',
        blog_back: '← Quay lại Blog',
        blog_read_more: 'Đọc Tiếp »',
        blog_empty: 'Chưa có bài viết nào 📝',
        blog_deleted: 'Đã xoá!',

        // ── Products Page
        prod_hero_title: '🍯 Đặc Sản Hà Giang',
        prod_hero_sub: 'Sản phẩm vùng cao nguyên chất, được chọn lọc kỹ lưỡng từ người dân địa phương',
        prod_search: 'Tìm sản phẩm...',
        prod_add: 'Thêm Sản Phẩm',
        prod_no_result: 'Không tìm thấy sản phẩm nào 😢',
        prod_badge: '🌿 Tự Nhiên',
        prod_detail: 'Chi Tiết',
        prod_cart: 'Giỏ',
        prod_buy: 'Mua',
        prod_order_title: '🛒 Đặt Mua',
        prod_name_ph: 'Họ và tên *',
        prod_phone_ph: 'Số điện thoại *',
        prod_qty_ph: 'Số lượng',
        prod_city_ph: 'Tỉnh/thành nhận hàng',
        prod_note_ph: 'Ghi chú...',
        prod_confirm_btn: '✅ Xác Nhận Đặt Hàng',
        prod_call_btn: '📞 Gọi Ngay 0385.737.705',
        prod_success_msg: 'Đặt hàng "{title}" thành công! Admin/Mod sẽ liên hệ sớm.',
        prod_added_cart: 'Đã thêm "{title}" vào giỏ!',
        prod_deleted: 'Đã xoá!',

        // ── Order Page
        order_hero_title: '🛒 Order Taobao',
        order_hero_sub: 'Đặt hàng Trung Quốc giá gốc – Vận chuyển nhanh – An toàn',
        order_process_title: 'Quy Trình Đặt Hàng',
        order_s1_title: 'Chọn hàng Taobao',
        order_s1_desc: 'Tìm sản phẩm yêu thích trên app/web Taobao, sao chép link',
        order_s2_title: 'Gửi link cho HTM',
        order_s2_desc: 'Paste link vào form bên dưới hoặc gửi qua Zalo 0385.737.705',
        order_s3_title: 'Thanh toán & chờ hàng',
        order_s3_desc: 'HTM đặt hàng và vận chuyển về Việt Nam trong 7-10 ngày',
        order_s4_title: 'Nhận hàng tại nhà',
        order_s4_desc: 'Hàng được đóng gói cẩn thận, giao tận nơi toàn quốc',
        order_form_title: '📋 Gửi Yêu Cầu Đặt Hàng',
        order_name_ph: 'Họ và tên *',
        order_phone_ph: 'Số điện thoại *',
        order_link_ph: 'Link sản phẩm Taobao *',
        order_desc_ph: 'Tên / mô tả hàng',
        order_qty_ph: 'Số lượng',
        order_note_ph: 'Ghi chú (màu sắc, size, yêu cầu đặc biệt...)',
        order_submit_btn: '🚀 Gửi Đơn Hàng',
        order_call_btn: '📞 Gọi Tư Vấn 0385.737.705',
        order_price_title: '💰 Bảng Giá Vận Chuyển',
        price_weight: 'Cân nặng',
        price_domestic: '🇻🇳 Nội địa',
        price_china: '🇨🇳 Trung Quốc',
        guarantee1: 'Bảo hiểm hàng hóa 100%',
        guarantee2: 'Theo dõi đơn hàng realtime',
        guarantee3: 'Hoàn tiền nếu hàng lỗi',
        order_success_h: 'Đã Gửi Thành Công!',
        order_success_p: 'HTM sẽ liên hệ trong 30 phút qua số bạn cung cấp.',
        order_toast: '✅ Đã gửi đơn! Admin/Mod sẽ liên hệ xác nhận trong 30 phút.',

        // ── Contact Page
        contact_hero_title: '📞 Liên Hệ HTM Trường Hải',
        contact_hero_sub: 'Luôn sẵn sàng tư vấn và đồng hành cùng bạn',
        contact_hotline: 'Hotline',
        contact_hotline_val: '0385.737.705',
        contact_zalo: 'Zalo',
        contact_zalo_val: 'Chat ngay 0385.737.705',
        contact_addr: 'Địa chỉ',
        contact_addr_val: 'Hà Giang, Việt Nam',
        contact_hours: 'Giờ làm việc',
        contact_hours_val: '7:00 – 22:00 hằng ngày',
        contact_form_title: '💬 Gửi Yêu Cầu Tư Vấn',
        contact_name_ph: 'Họ và tên *',
        contact_phone_ph: 'Điện thoại *',
        contact_email_ph: 'Email (không bắt buộc)',
        contact_svc_ph: '-- Chọn chủ đề --',
        contact_svc1: 'Hỏi về bài viết',
        contact_svc2: 'Hợp tác / Quảng cáo',
        contact_svc3: 'Góp ý',
        contact_svc4: 'Khác',
        contact_msg_ph: 'Nội dung *',
        contact_submit_btn: '📨 Gửi',
        contact_call_btn: '📞 Gọi Ngay 0385.737.705',
        contact_sent_h: 'Đã Gửi Thành Công!',
        contact_sent_p: 'HTM Trường Hải sẽ liên hệ bạn sớm nhất có thể.',
        contact_send_more: 'Gửi Tiếp',
        contact_map_title: '📍 Vị Trí',
        contact_map1: '🏔️ Hà Giang – Vùng cực Bắc Tổ Quốc',
        contact_map2: '⏱️ Cách Hà Nội khoảng 300km (6-7 tiếng lái xe)',
        contact_map3: '✈️ Bay đến Nội Bài rồi đi xe về Hà Giang',
        contact_toast: '✅ Đã nhận yêu cầu! HTM sẽ phản hồi sớm.',

        // ── App modals
        login_title: 'Đăng Nhập',
        login_username_ph: 'Tên đăng nhập',
        login_password_ph: 'Mật khẩu',
        login_btn: 'Đăng Nhập',
        admin_add: '➕ Thêm',
        admin_type_post: 'Bài Viết',
        admin_title_ph: 'Tiêu đề bài viết',
        admin_content_ph: 'Nội dung bài viết',
        admin_author_ph: 'Tên tác giả',
        admin_img_label: 'Ảnh bài đăng',
        admin_img_click: 'Click để tải ảnh lên',
        admin_img_or: '— hoặc nhập URL ảnh —',
        admin_change_img: 'Đổi ảnh',
        admin_save_btn: '✅ Lưu',
        admin_success: '✅ Đã đăng {type} thành công!',
        footer_copy: '© 2026',

        // ── WhatsApp
        contact_whatsapp: 'WhatsApp',
        contact_whatsapp_val: 'Nhắn tin 0385.737.705',

        // ── Blog edit
        blog_edit: '✏️ Sửa',
        admin_update_btn: '✅ Cập nhật',
        admin_edit_title: 'Chỉnh sửa bài viết',

        // ── Misc
        price_contact: 'Liên hệ',
        delete_tooltip: 'Xoá',

        // ── Featured tours (HomePage)
        featured_t1: 'Tour Đồng Văn – Mã Pí Lèng',
        featured_t1_price: '2.500.000đ',
        featured_t2: 'Homestay Hoàng Su Phì',
        featured_t2_price: '800.000đ/đêm',
        featured_t3: 'Trekking Đỉnh Mây',
        featured_t3_price: '1.800.000đ',
    },

    en: {
        // ── Navigation
        nav_home: '🏠 Home',
        nav_blog: '📝 Blog',
        nav_contact: '📞 Contact',
        btn_login: 'Login',
        btn_logout: 'Sign Out',

        // ── Blog Page
        blog_hero_title: '📝 Blog',
        blog_hero_sub: 'Stories, experiences and insights shared by HTM Truong Hai',
        blog_search: 'Search articles...',
        blog_add: 'New Post',
        blog_back: '← Back to Blog',
        blog_read_more: 'Read More »',
        blog_empty: 'No posts yet 📝',
        blog_deleted: 'Deleted!',
        tours_hero_sub: 'Terraced Rice Fields · Mã Pí Lèng Peak · Dong Van Stone Plateau',
        tours_search: 'Search tours...',
        tours_add: '+ Add Tour',
        tours_no_result: 'No tours found 😢',
        tours_filter_all: 'All',
        tours_filter_budget: '💰 Budget',
        tours_filter_premium: '⭐ Premium',
        tours_filter_trek: '🥾 Trekking',
        tours_sort: 'Sort',
        tours_sort_default: 'Default',
        tours_sort_price_asc: 'Price: Low → High',
        tours_sort_price_desc: 'Price: High → Low',
        tours_sort_rating: 'Top Rated',
        tours_results: 'tour(s)',

        // ── Tour Card
        card_from: 'From',
        card_per_person: '/person',
        card_duration: 'Duration',
        card_max: 'Max',
        card_people: 'people',
        card_rating: 'Rating',
        card_detail: 'View Details',
        card_book: '🗓 Book Now',
        card_includes: 'Includes:',

        // ── Includes labels
        inc_transport: '🚌 Transport',
        inc_meal: '🍽️ Meals',
        inc_guide: '🧭 Tour Guide',
        inc_hotel: '🏨 Accommodation',
        inc_ticket: '🎫 Entry Tickets',

        // ── Booking Modal
        book_title: '🗺️ Book Tour',
        book_step1: 'Date',
        book_step2: 'Your Info',
        book_step3: 'Confirm',
        book_departure_date: 'Departure Date *',
        book_guest_count: 'Number of Guests',
        book_adults: 'Adults',
        book_children: 'Children',
        book_next: 'Next →',
        book_full_name: 'Full Name *',
        book_phone: 'Phone Number *',
        book_email: 'Email (optional)',
        book_notes: 'Special Requests',
        book_notes_ph: 'Food allergies, private room, special requirements...',
        book_back: '← Back',
        book_summary_title: '📋 Booking Summary',
        book_tour_label: 'Tour',
        book_date_label: 'Departure Date',
        book_total_guests: 'Total Guests',
        book_price_per: 'Price / person',
        book_contact_label: 'Contact',
        book_note_label: 'Notes',
        book_confirm: '✅ Confirm Booking',
        book_call: '📞 Call 0385.737.705',
        book_no_date: '⚠️ Please select a departure date',
        book_required_msg: '⚠️ Please fill in all required fields',
        book_success_msg: 'Tour "{title}" booked! Admin/Mod will contact you soon.',
        book_adults_label: 'adults',
        book_children_label: 'children',
        book_and: 'and',
        book_deleted: 'Deleted!',

        // ── Home Page
        hero_badge: '📝 Blog & Sharing',
        hero_h1_blog: 'Blog by',
        hero_blog_name: 'HTM Truong Hai',
        hero_sub: 'Sharing experiences, stories and interesting things every day.',
        hero_btn_blog: '📝 Read Blog',
        hero_btn_contact: '📞 Contact',
        home_recent_posts: 'Latest Posts',
        home_see_all: 'View all',
        cta_title: 'Get in Touch',
        cta_sub: 'Have a question or want to collaborate? Contact HTM Truong Hai today.',
        cta_call: '📞 Call 0385.737.705',
        cta_consult: '📋 Send Request',
        logo_sub: 'Blog & Sharing',

        // ── Products Page
        prod_hero_title: '🍯 Ha Giang Specialties',
        prod_hero_sub: 'Pure highland products, carefully selected from local farmers',
        prod_search: 'Search products...',
        prod_add: 'Add Product',
        prod_no_result: 'No products found 😢',
        prod_badge: '🌿 Natural',
        prod_detail: 'Details',
        prod_cart: 'Cart',
        prod_buy: 'Buy',
        prod_order_title: '🛒 Purchase',
        prod_name_ph: 'Full Name *',
        prod_phone_ph: 'Phone Number *',
        prod_qty_ph: 'Quantity',
        prod_city_ph: 'Delivery city/province',
        prod_note_ph: 'Notes...',
        prod_confirm_btn: '✅ Confirm Order',
        prod_call_btn: '📞 Call 0385.737.705',
        prod_success_msg: 'Order for "{title}" placed! Admin/Mod will contact you soon.',
        prod_added_cart: '"{title}" added to cart!',
        prod_deleted: 'Deleted!',

        // ── Order Page
        order_hero_title: '🛒 Taobao Order',
        order_hero_sub: 'Chinese products at factory price – Fast shipping – Safe',
        order_process_title: 'Ordering Process',
        order_s1_title: 'Choose Taobao Products',
        order_s1_desc: 'Find your favorite products on the Taobao app/website, copy the link',
        order_s2_title: 'Send Link to HTM',
        order_s2_desc: 'Paste the link into the form below or send via Zalo 0385.737.705',
        order_s3_title: 'Pay & Wait for Delivery',
        order_s3_desc: 'HTM places the order and ships to Vietnam within 7-10 days',
        order_s4_title: 'Receive at Home',
        order_s4_desc: 'Goods are carefully packed and delivered nationwide',
        order_form_title: '📋 Submit Order Request',
        order_name_ph: 'Full Name *',
        order_phone_ph: 'Phone Number *',
        order_link_ph: 'Taobao product link *',
        order_desc_ph: 'Product name/description',
        order_qty_ph: 'Quantity',
        order_note_ph: 'Notes (color, size, special requirements...)',
        order_submit_btn: '🚀 Submit Order',
        order_call_btn: '📞 Call for Advice 0385.737.705',
        order_price_title: '💰 Shipping Price Table',
        price_weight: 'Weight',
        price_domestic: '🇻🇳 Domestic',
        price_china: '🇨🇳 From China',
        guarantee1: '100% Goods Insurance',
        guarantee2: 'Real-time order tracking',
        guarantee3: 'Refund if goods are defective',
        order_success_h: 'Successfully Sent!',
        order_success_p: 'HTM will contact you within 30 minutes.',
        order_toast: '✅ Order sent! Admin/Mod will confirm within 30 minutes.',

        // ── Contact Page
        contact_hero_title: '📞 Contact HTM Truong Hai',
        contact_hero_sub: 'Always ready to assist and accompany you',
        contact_hotline: 'Hotline',
        contact_hotline_val: '0385.737.705',
        contact_zalo: 'Zalo',
        contact_zalo_val: 'Chat now 0385.737.705',
        contact_addr: 'Address',
        contact_addr_val: 'Ha Giang, Vietnam',
        contact_hours: 'Working Hours',
        contact_hours_val: '7:00 AM – 10:00 PM Daily',
        contact_form_title: '💬 Send a Message',
        contact_name_ph: 'Full Name *',
        contact_phone_ph: 'Phone *',
        contact_email_ph: 'Email (optional)',
        contact_svc_ph: '-- Select topic --',
        contact_svc1: 'Question about a post',
        contact_svc2: 'Collaboration / Advertising',
        contact_svc3: 'Feedback',
        contact_svc4: 'Other',
        contact_msg_ph: 'Message *',
        contact_submit_btn: '📨 Send',
        contact_call_btn: '📞 Call 0385.737.705',
        contact_sent_h: 'Successfully Sent!',
        contact_sent_p: 'HTM Truong Hai will get back to you as soon as possible.',
        contact_send_more: 'Send Another',
        contact_map_title: '📍 Location',
        contact_map1: '🏔️ Ha Giang – Northernmost Region of Vietnam',
        contact_map2: '⏱️ About 300km from Hanoi (6-7 hours drive)',
        contact_map3: '✈️ Fly to Noi Bai airport then drive to Ha Giang',
        contact_toast: '✅ Message received! HTM will respond soon.',

        // ── App modals
        login_title: 'Sign In',
        login_username_ph: 'Username',
        login_password_ph: 'Password',
        login_btn: 'Sign In',
        admin_add: '➕ Add',
        admin_type_post: 'Blog Post',
        admin_title_ph: 'Post title',
        admin_content_ph: 'Post content',
        admin_author_ph: 'Author name',
        admin_img_label: 'Post image',
        admin_img_click: 'Click to upload image',
        admin_img_or: '— or enter image URL —',
        admin_change_img: 'Change image',
        admin_save_btn: '✅ Save',
        admin_success: '✅ Successfully published {type}!',
        footer_copy: '© 2026',

        // ── WhatsApp
        contact_whatsapp: 'WhatsApp',
        contact_whatsapp_val: 'Message 0385.737.705',

        // ── Blog edit
        blog_edit: '✏️ Edit',
        admin_update_btn: '✅ Update',
        admin_edit_title: 'Edit Post',

        // ── Misc
        price_contact: 'Contact us',
        delete_tooltip: 'Delete',
    },
}

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('vi')

    const t = (key) => translations[lang]?.[key] ?? translations.vi[key] ?? key
    const toggleLang = () => setLang(l => (l === 'vi' ? 'en' : 'vi'))

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLang = () => useContext(LanguageContext)
