import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)

export const translations = {
    vi: {
        // ── Navigation
        nav_home: '🏠 Trang Chủ',
        nav_tours: '🗺️ Du Lịch',
        nav_order: '🛒 Order Taobao',
        nav_products: '🍯 Đặc Sản',
        nav_blog: '📝 Blog',
        nav_contact: '📞 Liên Hệ',
        nav_mgmt_cart: '🛒 QL Giỏ Hàng',
        nav_mgmt_tour: '🗺️ QL Đặt Tour',
        nav_mgmt_taobao: '📦 QL Taobao',
        btn_login: 'Đăng Nhập',
        btn_logout: 'Thoát',

        // ── Tours Hero
        tours_hero_title: '🗺️ Tour Du Lịch Hà Giang',
        tours_hero_sub: 'Ruộng bậc thang · Đỉnh Mã Pí Lèng · Bình nguyên đá Đồng Văn',
        tours_search: 'Tìm kiếm tour...',
        tours_add: '+ Thêm Tour',
        tours_no_result: 'Không tìm thấy tour nào 😢',
        tours_filter_all: 'Tất cả',
        tours_filter_budget: '💰 Tiết kiệm',
        tours_filter_premium: '⭐ Cao cấp',
        tours_filter_trek: '🥾 Trekking',
        tours_sort: 'Sắp xếp',
        tours_sort_default: 'Mặc định',
        tours_sort_price_asc: 'Giá tăng dần',
        tours_sort_price_desc: 'Giá giảm dần',
        tours_sort_rating: 'Đánh giá cao',
        tours_results: 'tour',

        // ── Tour Card
        card_from: 'Từ',
        card_per_person: '/người',
        card_duration: 'Thời gian',
        card_max: 'Tối đa',
        card_people: 'người',
        card_rating: 'Đánh giá',
        card_detail: 'Chi Tiết',
        card_book: '🗓 Đặt Ngay',
        card_includes: 'Bao gồm:',

        // ── Includes labels
        inc_transport: '🚌 Xe đưa đón',
        inc_meal: '🍽️ Ăn uống',
        inc_guide: '🧭 HDV',
        inc_hotel: '🏨 Lưu trú',
        inc_ticket: '🎫 Vé tham quan',

        // ── Booking Modal
        book_title: '🗺️ Đặt Tour',
        book_step1: 'Chọn ngày',
        book_step2: 'Thông tin',
        book_step3: 'Xác nhận',
        book_departure_date: 'Ngày khởi hành *',
        book_guest_count: 'Số lượng khách',
        book_adults: 'Người lớn',
        book_children: 'Trẻ em',
        book_next: 'Tiếp theo →',
        book_full_name: 'Họ và tên *',
        book_phone: 'Số điện thoại *',
        book_email: 'Email (tùy chọn)',
        book_notes: 'Yêu cầu đặc biệt',
        book_notes_ph: 'Dị ứng thức ăn, phòng riêng, yêu cầu đặc biệt...',
        book_back: '← Quay lại',
        book_summary_title: '📋 Tóm tắt đặt tour',
        book_tour_label: 'Tour',
        book_date_label: 'Ngày khởi hành',
        book_total_guests: 'Tổng khách',
        book_price_per: 'Giá / người',
        book_contact_label: 'Liên hệ',
        book_note_label: 'Ghi chú',
        book_confirm: '✅ Xác Nhận Đặt Tour',
        book_call: '📞 Gọi Ngay 0385.737.705',
        book_no_date: '⚠️ Vui lòng chọn ngày khởi hành',
        book_required_msg: '⚠️ Vui lòng điền đầy đủ thông tin bắt buộc',
        book_success_msg: 'Đặt tour "{title}" thành công! Admin/Mod sẽ liên hệ sớm.',
        book_adults_label: 'người lớn',
        book_children_label: 'trẻ em',
        book_and: 'và',
        book_deleted: 'Đã xoá!',

        // ── Home Page
        hero_badge: '🏔️ Khám Phá Vùng Cao',
        hero_h1_explore: 'Khám Phá',
        hero_h1_order: 'Đặt Hàng',
        hero_sub: 'HTM Trường Hải – Đồng hành cùng bạn!',
        hero_btn_tour: '🗺️ Tour Hà Giang',
        hero_btn_order: '🛒 Order Taobao',
        stat_customers: 'Khách hài lòng',
        stat_tours: 'Tour đã tổ chức',
        stat_rating: 'Đánh giá',
        home_svc_title: 'Dịch Vụ Của Chúng Tôi',
        home_svc_sub: 'Tất cả trong một nền tảng – du lịch, mua sắm, đặc sản',
        home_svc_tour_title: 'Tour Hà Giang',
        home_svc_tour_desc: 'Trọn gói 2-4 ngày, ruộng bậc thang, đỉnh núi huyền ảo',
        home_svc_order_title: 'Order Taobao',
        home_svc_order_desc: 'Đặt hàng Trung Quốc giá gốc, vận chuyển 7-10 ngày',
        home_svc_prod_title: 'Đặc Sản Hà Giang',
        home_svc_prod_desc: 'Mật ong bạc hà, trà hoa vàng, thịt trâu gác bếp',
        home_svc_blog_title: 'Blog & Tin Tức',
        home_svc_blog_desc: 'Kinh nghiệm du lịch, hướng dẫn order, tin tức mới',
        home_featured: '🗺️ Tour Nổi Bật',
        home_see_all: 'Xem tất cả',
        cta_title: 'Sẵn Sàng Khám Phá',
        cta_sub: 'Liên hệ ngay để được tư vấn miễn phí và nhận ưu đãi đặc biệt',
        cta_call: '📞 Gọi 0385.737.705',
        cta_consult: '📋 Yêu Cầu Tư Vấn',
        logo_sub: 'Du lịch & Order Quốc tế',

        // ── Blog Page
        blog_hero_title: '📝 Blog & Tin Tức',
        blog_hero_sub: 'Kinh nghiệm du lịch, hướng dẫn order Taobao, khám phá vùng cao',
        blog_search: 'Tìm bài viết...',
        blog_add: 'Đăng Bài',
        blog_back: '← Quay lại Blog',
        blog_read_more: 'Đọc Tiếp »',
        blog_empty: 'Chưa có bài viết nào 📝',
        blog_deleted: 'Đã xoá!',

        // ── Products Page
        prod_hero_title: '🍯 Đặc Sản Hà Giang',
        prod_hero_sub: 'Sản phẩm vùng cao nguyên chất, được chọn lọc kỹ lưỡng từ người dân địa phương',
        prod_search: 'Tìm sản phẩm...',
        prod_add: 'Thêm Sản Phẩm',
        prod_no_result: 'Không tìm thấy sản phẩm nào 😢',
        prod_badge: '🌿 Tự Nhiên',
        prod_detail: 'Chi Tiết',
        prod_cart: 'Giỏ',
        prod_buy: 'Mua',
        prod_order_title: '🛒 Đặt Mua',
        prod_name_ph: 'Họ và tên *',
        prod_phone_ph: 'Số điện thoại *',
        prod_qty_ph: 'Số lượng',
        prod_city_ph: 'Tỉnh/thành nhận hàng',
        prod_note_ph: 'Ghi chú...',
        prod_confirm_btn: '✅ Xác Nhận Đặt Hàng',
        prod_call_btn: '📞 Gọi Ngay 0385.737.705',
        prod_success_msg: 'Đặt hàng "{title}" thành công! Admin/Mod sẽ liên hệ sớm.',
        prod_added_cart: 'Đã thêm "{title}" vào giỏ!',
        prod_deleted: 'Đã xoá!',

        // ── Order Page
        order_hero_title: '🛒 Order Taobao',
        order_hero_sub: 'Đặt hàng Trung Quốc giá gốc – Vận chuyển nhanh – An toàn',
        order_process_title: 'Quy Trình Đặt Hàng',
        order_s1_title: 'Chọn hàng Taobao',
        order_s1_desc: 'Tìm sản phẩm yêu thích trên app/web Taobao, sao chép link',
        order_s2_title: 'Gửi link cho HTM',
        order_s2_desc: 'Paste link vào form bên dưới hoặc gửi qua Zalo 0385.737.705',
        order_s3_title: 'Thanh toán & chờ hàng',
        order_s3_desc: 'HTM đặt hàng và vận chuyển về Việt Nam trong 7-10 ngày',
        order_s4_title: 'Nhận hàng tại nhà',
        order_s4_desc: 'Hàng được đóng gói cẩn thận, giao tận nơi toàn quốc',
        order_form_title: '📋 Gửi Yêu Cầu Đặt Hàng',
        order_name_ph: 'Họ và tên *',
        order_phone_ph: 'Số điện thoại *',
        order_link_ph: 'Link sản phẩm Taobao *',
        order_desc_ph: 'Tên / mô tả hàng',
        order_qty_ph: 'Số lượng',
        order_note_ph: 'Ghi chú (màu sắc, size, yêu cầu đặc biệt...)',
        order_submit_btn: '🚀 Gửi Đơn Hàng',
        order_call_btn: '📞 Gọi Tư Vấn 0385.737.705',
        order_price_title: '💰 Bảng Giá Vận Chuyển',
        price_weight: 'Cân nặng',
        price_domestic: '🇻🇳 Nội địa',
        price_china: '🇨🇳 Trung Quốc',
        guarantee1: 'Bảo hiểm hàng hóa 100%',
        guarantee2: 'Theo dõi đơn hàng realtime',
        guarantee3: 'Hoàn tiền nếu hàng lỗi',
        order_success_h: 'Đã Gửi Thành Công!',
        order_success_p: 'HTM sẽ liên hệ trong 30 phút qua số bạn cung cấp.',
        order_toast: '✅ Đã gửi đơn! Admin/Mod sẽ liên hệ xác nhận trong 30 phút.',

        // ── Contact Page
        contact_hero_title: '📞 Liên Hệ HTM Trường Hải',
        contact_hero_sub: 'Luôn sẵn sàng tư vấn và đồng hành cùng bạn',
        contact_hotline: 'Hotline',
        contact_hotline_val: '0385.737.705',
        contact_zalo: 'Zalo',
        contact_zalo_val: 'Chat ngay 0385.737.705',
        contact_addr: 'Địa chỉ',
        contact_addr_val: 'Hà Giang, Việt Nam',
        contact_hours: 'Giờ làm việc',
        contact_hours_val: '7:00 – 22:00 hằng ngày',
        contact_form_title: '💬 Gửi Yêu Cầu Tư Vấn',
        contact_name_ph: 'Họ và tên *',
        contact_phone_ph: 'Điện thoại *',
        contact_email_ph: 'Email (không bắt buộc)',
        contact_svc_ph: '-- Chọn dịch vụ tư vấn --',
        contact_svc1: 'Tour Du Lịch Hà Giang',
        contact_svc2: 'Order Taobao',
        contact_svc3: 'Đặc Sản Hà Giang',
        contact_svc4: 'Khác',
        contact_msg_ph: 'Nội dung cần tư vấn *',
        contact_submit_btn: '📨 Gửi Yêu Cầu',
        contact_call_btn: '📞 Gọi Ngay 0385.737.705',
        contact_sent_h: 'Đã Gửi Thành Công!',
        contact_sent_p: 'HTM Trường Hải sẽ liên hệ bạn trong 30 phút làm việc.',
        contact_send_more: 'Gửi Tiếp',
        contact_map_title: '📍 Vị Trí',
        contact_map1: '🏔️ Hà Giang – Vùng cực Bắc Tổ Quốc',
        contact_map2: '⏱️ Cách Hà Nội khoảng 300km (6-7 tiếng lái xe)',
        contact_map3: '✈️ Bay đến Nội Bài rồi đi xe về Hà Giang',
        contact_toast: '✅ Đã nhận yêu cầu tư vấn! HTM sẽ phản hồi trong 30 phút.',

        // ── App modals
        login_title: 'Đăng Nhập',
        login_username_ph: 'Tên đăng nhập',
        login_password_ph: 'Mật khẩu',
        login_btn: 'Đăng Nhập',
        admin_add: '➕ Thêm',
        admin_type_tour: 'Tour Du Lịch',
        admin_type_product: 'Sản Phẩm',
        admin_type_post: 'Bài Viết',
        admin_title_ph: 'Tiêu đề / Tên',
        admin_desc_ph: 'Mô tả ngắn',
        admin_content_ph: 'Nội dung bài viết',
        admin_price_ph: 'Giá (VD: 500.000đ)',
        admin_author_ph: 'Tên tác giả',
        admin_img_label: 'Ảnh bài đăng',
        admin_img_click: 'Click để tải ảnh lên',
        admin_img_or: '— hoặc nhập URL ảnh —',
        admin_change_img: 'Đổi ảnh',
        admin_save_btn: '✅ Lưu',
        admin_success: '✅ Đã thêm {type} thành công!',
        detail_book_btn: '📞 Đặt / Mua Ngay',
        detail_back_btn: '← Quay Lại',
        cart_title: 'Giỏ Hàng',
        cart_empty_msg: 'Giỏ hàng đang trống',
        cart_shop_btn: 'Mua Sắm Ngay →',
        cart_clear_btn: '🗑️ Xóa tất cả',
        cart_checkout_btn: 'Đặt Hàng →',
        cart_items_suffix: 'sp',
        cart_info_title: '📋 Thông tin nhận hàng',
        cart_name_ph: 'Họ và tên *',
        cart_phone_ph: 'Số điện thoại *',
        cart_addr_ph: 'Địa chỉ nhận hàng',
        cart_note_ph: 'Ghi chú...',
        cart_confirm_btn: '✅ Xác Nhận Đặt Hàng',
        cart_back_btn: '← Giỏ hàng',
        cart_toast: '✅ Đã gửi đơn! Admin/Mod sẽ liên hệ xác nhận sớm.',
        notif_title: '🔔 Thông báo',
        notif_new_suffix: 'mới',
        notif_read_all: 'Đọc tất cả',
        notif_empty: 'Chưa có thông báo nào',
        footer_copy: '© 2026',

        // ── Header tooltips
        header_cart_title: 'Giỏ hàng',
        header_notif_title: 'Thông báo',

        // ── Manage pages – shared
        mgmt_access_denied: '⛔ Chỉ Admin/Mod mới xem được trang này.',
        mgmt_back_home: '← Trang chủ',
        mgmt_back: 'Quay lại',
        mgmt_total: 'Tổng',
        mgmt_orders: 'đơn',
        mgmt_pending_count: 'đang chờ xử lý',
        mgmt_bookings: 'booking',

        // ── Status options
        status_pending: 'Chờ xử lý',
        status_confirmed: 'Đã xác nhận',
        status_shipped: 'Đang vận chuyển',
        status_done: 'Hoàn thành',
        status_cancelled: 'Đã huỷ',

        // ── ManageCart
        mgmt_cart_title: '🛒 Quản Lý Giỏ Hàng',
        mgmt_cart_empty: 'Chưa có đơn giỏ hàng nào 📦',
        mgmt_cart_products: 'Sản phẩm:',

        // ── ManageTaobao
        mgmt_taobao_title: '📦 Quản Lý Kho Taobao',
        mgmt_taobao_empty: 'Chưa có đơn Taobao nào 📦',
        mgmt_taobao_item: 'Mặt hàng:',
        mgmt_taobao_qty: 'Số lượng:',

        // ── ManageTour
        mgmt_tour_title: '🗺️ Quản Lý Đặt Tour',
        mgmt_tour_empty: 'Chưa có đặt tour nào 🗺️',
        mgmt_tour_departure: 'Khởi hành:',
        mgmt_tour_guests: 'Số người:',

        // ── WhatsApp
        contact_whatsapp: 'WhatsApp',
        contact_whatsapp_val: 'Nhắn tin 0385.737.705',
        whatsapp_btn: '💬 WhatsApp',

        // ── Blog edit
        blog_edit: '✏️ Sửa',
        admin_update_btn: '✅ Cập nhật',
        admin_edit_title: 'Chỉnh sửa bài viết',
        admin_edit_title_prefix: '✏️ Chỉnh sửa',

        // ── Misc
        hero_hagiang: 'Hà Giang',
        price_contact: 'Liên hệ',
        delete_tooltip: 'Xoá',

        // ── Featured tours (HomePage)
        featured_t1: 'Tour Đồng Văn – Mã Pí Lèng',
        featured_t1_price: '2.500.000đ',
        featured_t2: 'Homestay Hoàng Su Phì',
        featured_t2_price: '800.000đ/đêm',
        featured_t3: 'Trekking Đỉnh Mây',
        featured_t3_price: '1.800.000đ',
    },

    en: {
        // ── Navigation
        nav_home: '🏠 Home',
        nav_tours: '🗺️ Tours',
        nav_order: '🛒 Taobao Order',
        nav_products: '🍯 Specialties',
        nav_blog: '📝 Blog',
        nav_contact: '📞 Contact',
        nav_mgmt_cart: '🛒 Cart Mgmt',
        nav_mgmt_tour: '🗺️ Tour Mgmt',
        nav_mgmt_taobao: '📦 Taobao Mgmt',
        btn_login: 'Login',
        btn_logout: 'Sign Out',

        // ── Tours Hero
        tours_hero_title: '🗺️ Ha Giang Travel Tours',
        tours_hero_sub: 'Terraced Rice Fields · Mã Pí Lèng Peak · Dong Van Stone Plateau',
        tours_search: 'Search tours...',
        tours_add: '+ Add Tour',
        tours_no_result: 'No tours found 😢',
        tours_filter_all: 'All',
        tours_filter_budget: '💰 Budget',
        tours_filter_premium: '⭐ Premium',
        tours_filter_trek: '🥾 Trekking',
        tours_sort: 'Sort',
        tours_sort_default: 'Default',
        tours_sort_price_asc: 'Price: Low → High',
        tours_sort_price_desc: 'Price: High → Low',
        tours_sort_rating: 'Top Rated',
        tours_results: 'tour(s)',

        // ── Tour Card
        card_from: 'From',
        card_per_person: '/person',
        card_duration: 'Duration',
        card_max: 'Max',
        card_people: 'people',
        card_rating: 'Rating',
        card_detail: 'View Details',
        card_book: '🗓 Book Now',
        card_includes: 'Includes:',

        // ── Includes labels
        inc_transport: '🚌 Transport',
        inc_meal: '🍽️ Meals',
        inc_guide: '🧭 Tour Guide',
        inc_hotel: '🏨 Accommodation',
        inc_ticket: '🎫 Entry Tickets',

        // ── Booking Modal
        book_title: '🗺️ Book Tour',
        book_step1: 'Date',
        book_step2: 'Your Info',
        book_step3: 'Confirm',
        book_departure_date: 'Departure Date *',
        book_guest_count: 'Number of Guests',
        book_adults: 'Adults',
        book_children: 'Children',
        book_next: 'Next →',
        book_full_name: 'Full Name *',
        book_phone: 'Phone Number *',
        book_email: 'Email (optional)',
        book_notes: 'Special Requests',
        book_notes_ph: 'Food allergies, private room, special requirements...',
        book_back: '← Back',
        book_summary_title: '📋 Booking Summary',
        book_tour_label: 'Tour',
        book_date_label: 'Departure Date',
        book_total_guests: 'Total Guests',
        book_price_per: 'Price / person',
        book_contact_label: 'Contact',
        book_note_label: 'Notes',
        book_confirm: '✅ Confirm Booking',
        book_call: '📞 Call 0385.737.705',
        book_no_date: '⚠️ Please select a departure date',
        book_required_msg: '⚠️ Please fill in all required fields',
        book_success_msg: 'Tour "{title}" booked! Admin/Mod will contact you soon.',
        book_adults_label: 'adults',
        book_children_label: 'children',
        book_and: 'and',
        book_deleted: 'Deleted!',

        // ── Home Page
        hero_badge: '🏔️ Explore Northern Highlands',
        hero_h1_explore: 'Explore',
        hero_h1_order: 'Order from',
        hero_sub: 'HTM Truong Hai – Your trusted companion!',
        hero_btn_tour: '🗺️ Ha Giang Tours',
        hero_btn_order: '🛒 Taobao Order',
        stat_customers: 'Happy guests',
        stat_tours: 'Tours organized',
        stat_rating: 'Rating',
        home_svc_title: 'Our Services',
        home_svc_sub: 'All in one platform – travel, shopping, specialties',
        home_svc_tour_title: 'Ha Giang Tours',
        home_svc_tour_desc: 'Full packages 2-4 days, terraced fields, misty mountain peaks',
        home_svc_order_title: 'Taobao Order',
        home_svc_order_desc: 'Chinese products at factory price, delivered in 7-10 days',
        home_svc_prod_title: 'Ha Giang Specialties',
        home_svc_prod_desc: 'Buckwheat honey, golden tea, smoked buffalo meat',
        home_svc_blog_title: 'Blog & News',
        home_svc_blog_desc: 'Travel tips, ordering guides, latest updates',
        home_featured: '🗺️ Featured Tours',
        home_see_all: 'View all',
        cta_title: 'Ready to Explore',
        cta_sub: 'Contact us for a free consultation and special offers',
        cta_call: '📞 Call 0385.737.705',
        cta_consult: '📋 Request Consultation',
        logo_sub: 'Travel & International Order',

        // ── Blog Page
        blog_hero_title: '📝 Blog & News',
        blog_hero_sub: 'Travel tips, Taobao ordering guides, highland discoveries',
        blog_search: 'Search articles...',
        blog_add: 'Post Article',
        blog_back: '← Back to Blog',
        blog_read_more: 'Read More »',
        blog_empty: 'No posts yet 📝',
        blog_deleted: 'Deleted!',

        // ── Products Page
        prod_hero_title: '🍯 Ha Giang Specialties',
        prod_hero_sub: 'Pure highland products, carefully selected from local farmers',
        prod_search: 'Search products...',
        prod_add: 'Add Product',
        prod_no_result: 'No products found 😢',
        prod_badge: '🌿 Natural',
        prod_detail: 'Details',
        prod_cart: 'Cart',
        prod_buy: 'Buy',
        prod_order_title: '🛒 Purchase',
        prod_name_ph: 'Full Name *',
        prod_phone_ph: 'Phone Number *',
        prod_qty_ph: 'Quantity',
        prod_city_ph: 'Delivery city/province',
        prod_note_ph: 'Notes...',
        prod_confirm_btn: '✅ Confirm Order',
        prod_call_btn: '📞 Call 0385.737.705',
        prod_success_msg: 'Order for "{title}" placed! Admin/Mod will contact you soon.',
        prod_added_cart: '"{title}" added to cart!',
        prod_deleted: 'Deleted!',

        // ── Order Page
        order_hero_title: '🛒 Taobao Order',
        order_hero_sub: 'Chinese products at factory price – Fast shipping – Safe',
        order_process_title: 'Ordering Process',
        order_s1_title: 'Choose Taobao Products',
        order_s1_desc: 'Find your favorite products on the Taobao app/website, copy the link',
        order_s2_title: 'Send Link to HTM',
        order_s2_desc: 'Paste the link into the form below or send via Zalo 0385.737.705',
        order_s3_title: 'Pay & Wait for Delivery',
        order_s3_desc: 'HTM places the order and ships to Vietnam within 7-10 days',
        order_s4_title: 'Receive at Home',
        order_s4_desc: 'Goods are carefully packed and delivered nationwide',
        order_form_title: '📋 Submit Order Request',
        order_name_ph: 'Full Name *',
        order_phone_ph: 'Phone Number *',
        order_link_ph: 'Taobao product link *',
        order_desc_ph: 'Product name/description',
        order_qty_ph: 'Quantity',
        order_note_ph: 'Notes (color, size, special requirements...)',
        order_submit_btn: '🚀 Submit Order',
        order_call_btn: '📞 Call for Advice 0385.737.705',
        order_price_title: '💰 Shipping Price Table',
        price_weight: 'Weight',
        price_domestic: '🇻🇳 Domestic',
        price_china: '🇨🇳 From China',
        guarantee1: '100% Goods Insurance',
        guarantee2: 'Real-time order tracking',
        guarantee3: 'Refund if goods are defective',
        order_success_h: 'Successfully Sent!',
        order_success_p: 'HTM will contact you within 30 minutes.',
        order_toast: '✅ Order sent! Admin/Mod will confirm within 30 minutes.',

        // ── Contact Page
        contact_hero_title: '📞 Contact HTM Truong Hai',
        contact_hero_sub: 'Always ready to advise and accompany you',
        contact_hotline: 'Hotline',
        contact_hotline_val: '0385.737.705',
        contact_zalo: 'Zalo',
        contact_zalo_val: 'Chat now 0385.737.705',
        contact_addr: 'Address',
        contact_addr_val: 'Ha Giang, Vietnam',
        contact_hours: 'Working Hours',
        contact_hours_val: '7:00 AM – 10:00 PM Daily',
        contact_form_title: '💬 Send Consultation Request',
        contact_name_ph: 'Full Name *',
        contact_phone_ph: 'Phone *',
        contact_email_ph: 'Email (optional)',
        contact_svc_ph: '-- Select consultation service --',
        contact_svc1: 'Ha Giang Travel Tour',
        contact_svc2: 'Taobao Order',
        contact_svc3: 'Ha Giang Specialties',
        contact_svc4: 'Other',
        contact_msg_ph: 'Consultation content *',
        contact_submit_btn: '📨 Send Request',
        contact_call_btn: '📞 Call 0385.737.705',
        contact_sent_h: 'Successfully Sent!',
        contact_sent_p: 'HTM Truong Hai will contact you within 30 working minutes.',
        contact_send_more: 'Send Another',
        contact_map_title: '📍 Location',
        contact_map1: '🏔️ Ha Giang – Northernmost Region of Vietnam',
        contact_map2: '⏱️ About 300km from Hanoi (6-7 hours drive)',
        contact_map3: '✈️ Fly to Noi Bai airport then drive to Ha Giang',
        contact_toast: '✅ Consultation request received! HTM will respond within 30 minutes.',

        // ── App modals
        login_title: 'Sign In',
        login_username_ph: 'Username',
        login_password_ph: 'Password',
        login_btn: 'Sign In',
        admin_add: '➕ Add',
        admin_type_tour: 'Travel Tour',
        admin_type_product: 'Product',
        admin_type_post: 'Blog Post',
        admin_title_ph: 'Title / Name',
        admin_desc_ph: 'Short description',
        admin_content_ph: 'Post content',
        admin_price_ph: 'Price (e.g. 500.000đ)',
        admin_author_ph: 'Author name',
        admin_img_label: 'Post image',
        admin_img_click: 'Click to upload image',
        admin_img_or: '— or enter image URL —',
        admin_change_img: 'Change image',
        admin_save_btn: '✅ Save',
        admin_success: '✅ Successfully added {type}!',
        detail_book_btn: '📞 Book / Buy Now',
        detail_back_btn: '← Go Back',
        cart_title: 'Cart',
        cart_empty_msg: 'Your cart is empty',
        cart_shop_btn: 'Shop Now →',
        cart_clear_btn: '🗑️ Clear all',
        cart_checkout_btn: 'Checkout →',
        cart_items_suffix: 'items',
        cart_info_title: '📋 Delivery Information',
        cart_name_ph: 'Full Name *',
        cart_phone_ph: 'Phone Number *',
        cart_addr_ph: 'Delivery address',
        cart_note_ph: 'Notes...',
        cart_confirm_btn: '✅ Confirm Order',
        cart_back_btn: '← Cart',
        cart_toast: '✅ Order placed! Admin/Mod will confirm soon.',
        notif_title: '🔔 Notifications',
        notif_new_suffix: 'new',
        notif_read_all: 'Mark all read',
        notif_empty: 'No notifications yet',
        footer_copy: '© 2026',

        // ── Header tooltips
        header_cart_title: 'Cart',
        header_notif_title: 'Notifications',

        // ── Manage pages – shared
        mgmt_access_denied: '⛔ Only Admin/Mod can view this page.',
        mgmt_back_home: '← Home',
        mgmt_back: 'Go Back',
        mgmt_total: 'Total',
        mgmt_orders: 'order(s)',
        mgmt_pending_count: 'pending',
        mgmt_bookings: 'booking(s)',

        // ── Status options
        status_pending: 'Pending',
        status_confirmed: 'Confirmed',
        status_shipped: 'Shipped',
        status_done: 'Completed',
        status_cancelled: 'Cancelled',

        // ── ManageCart
        mgmt_cart_title: '🛒 Cart Management',
        mgmt_cart_empty: 'No cart orders yet 📦',
        mgmt_cart_products: 'Products:',

        // ── ManageTaobao
        mgmt_taobao_title: '📦 Taobao Order Management',
        mgmt_taobao_empty: 'No Taobao orders yet 📦',
        mgmt_taobao_item: 'Item:',
        mgmt_taobao_qty: 'Qty:',

        // ── ManageTour
        mgmt_tour_title: '🗺️ Tour Booking Management',
        mgmt_tour_empty: 'No tour bookings yet 🗺️',
        mgmt_tour_departure: 'Departure:',
        mgmt_tour_guests: 'Guests:',

        // ── WhatsApp
        contact_whatsapp: 'WhatsApp',
        contact_whatsapp_val: 'Message 0385.737.705',
        whatsapp_btn: '💬 WhatsApp',

        // ── Blog edit
        blog_edit: '✏️ Edit',
        admin_update_btn: '✅ Update',
        admin_edit_title: 'Edit Post',
        admin_edit_title_prefix: '✏️ Edit',

        // ── Misc
        hero_hagiang: 'Ha Giang',
        price_contact: 'Contact us',
        delete_tooltip: 'Delete',

        // ── Featured tours (HomePage)
        featured_t1: 'Dong Van – Ma Pi Leng Tour',
        featured_t1_price: '2,500,000đ',
        featured_t2: 'Hoang Su Phi Homestay',
        featured_t2_price: '800,000đ/night',
        featured_t3: 'Cloud Peak Trekking',
        featured_t3_price: '1,800,000đ',
    },
}

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('vi')

    const t = (key) => translations[lang]?.[key] ?? translations.vi[key] ?? key
    const toggleLang = () => setLang(l => (l === 'vi' ? 'en' : 'vi'))

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLang = () => useContext(LanguageContext)
