import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)

export const translations = {
    vi: {
        // ── Navigation
        nav_home: '🏠 Trang Chủ',
        nav_blog: '📝 Blog',
        nav_contact: '📞 Liên Hệ',
        btn_login: 'Đăng Nhập',
        btn_logout: 'Thoát',

        // ── Tours Hero
        tours_hero_title: '🗺️ Discover Hà Giang',
        tours_hero_sub: 'Ruộng bậc thang · Đỉnh Mã Pí Lèng · Bình nguyên đá Đồng Văn',
        tours_search: 'Tìm kiếm...',
        tours_add: '+ Thêm Mới',
        tours_no_result: 'Không tìm thấy 😢',
        tours_filter_all: 'Tất cả',
        tours_filter_budget: '💰 Tiết kiệm',
        tours_filter_premium: '⭐ Cao cấp',
        tours_filter_trek: '🥾 Trekking',
        tours_sort: 'Sắp xếp',
        tours_sort_default: 'Mặc định',
        tours_sort_price_asc: 'Giá tăng dần',
        tours_sort_price_desc: 'Giá giảm dần',
        tours_sort_rating: 'Đánh giá cao',
        tours_results: 'discover',

        // ── Tour Card
        card_from: 'Từ',
        card_per_person: '/người',
        card_duration: 'Thời gian',
        card_max: 'Tối đa',
        card_people: 'người',
        card_rating: 'Đánh giá',
        card_detail: 'Chi Tiết',
        card_book: '🗓 Đặt Ngay',
        card_includes: 'Bao gồm:',

        // ── Includes labels
        inc_transport: '🚌 Xe đưa đón',
        inc_meal: '🍽️ Ăn uống',
        inc_guide: '🧭 HDV',
        inc_hotel: '🏨 Lưu trú',
        inc_ticket: '🎫 Vé tham quan',

        // ── Booking Modal
        book_title: '🗺️ Đặt Lịch',
        book_step1: 'Chọn ngày',
        book_step2: 'Thông tin',
        book_step3: 'Xác nhận',
        book_departure_date: 'Ngày khởi hành *',
        book_guest_count: 'Số lượng khách',
        book_adults: 'Người lớn',
        book_children: 'Trẻ em',
        book_next: 'Tiếp theo →',
        book_full_name: 'Họ và tên *',
        book_phone: 'Số điện thoại *',
        book_email: 'Email (tùy chọn)',
        book_notes: 'Yêu cầu đặc biệt',
        book_notes_ph: 'Dị ứng thức ăn, phòng riêng, yêu cầu đặc biệt...',
        book_back: '← Quay lại',
        book_summary_title: '📋 Tóm tắt đặt lịch',
        book_tour_label: 'Discover',
        book_date_label: 'Ngày khởi hành',
        book_total_guests: 'Tổng khách',
        book_price_per: 'Giá / người',
        book_contact_label: 'Liên hệ',
        book_note_label: 'Ghi chú',
        book_confirm: '✅ Xác Nhận Đặt Lịch',
        book_call: '📞 Gọi Ngay 0385.737.705',
        book_no_date: '⚠️ Vui lòng chọn ngày khởi hành',
        book_required_msg: '⚠️ Vui lòng điền đầy đủ thông tin bắt buộc',
        book_success_msg: 'Đặt "{title}" thành công! Admin/Mod sẽ liên hệ sớm.',
        book_adults_label: 'người lớn',
        book_children_label: 'trẻ em',
        book_and: 'và',
        book_deleted: 'Đã xoá!',

        // ── Home Page
        hero_badge: '📝 Blog & Chia Sẻ',
        hero_h1_blog: 'Blog Chia Sẻ Của',
        hero_blog_name: 'HTM Trường Hải',
        hero_sub: 'Chia sẻ kinh nghiệm, câu chuyện và những điều thú vị mỗi ngày.',
        hero_btn_blog: '📝 Đọc Blog',
        hero_btn_contact: '📞 Liên Hệ',
        home_recent_posts: 'Bài Viết Mới Nhất',
        home_see_all: 'Xem tất cả',
        cta_title: 'Liên Hệ Với Chúng Tôi',
        cta_sub: 'Có câu hỏi hoặc muốn hợp tác? Liên hệ ngay với HTM Trường Hải',
        cta_call: '📞 Gọi 0385.737.705',
        cta_consult: '📋 Gửi Yêu Cầu',
        logo_sub: 'Blog & Chia Sẻ',

        // ── Blog Page
        blog_hero_title: '📝 Blog & Tin Tức',
        blog_hero_sub: 'Kinh nghiệm du lịch, khám phá vùng cao',
        blog_search: 'Tìm bài viết...',
        blog_add: 'Đăng Bài',
        blog_back: '← Quay lại Blog',
        blog_read_more: 'Đọc Tiếp »',
        blog_empty: 'Chưa có bài viết nào 📝',
        blog_deleted: 'Đã xoá!',

        // ── Products Page
        prod_hero_title: '🍯 Đặc Sản Hà Giang',
        prod_hero_sub: 'Sản phẩm vùng cao nguyên chất, được chọn lọc kỹ lưỡng từ người dân địa phương',
        prod_search: 'Tìm sản phẩm...',
        prod_add: 'Thêm Sản Phẩm',
        prod_no_result: 'Không tìm thấy sản phẩm nào 😢',
        prod_badge: '🌿 Tự Nhiên',
        prod_detail: 'Chi Tiết',
        prod_cart: 'Giỏ',
        prod_buy: 'Mua',
        prod_order_title: '🛒 Đặt Mua',
        prod_name_ph: 'Họ và tên *',
        prod_phone_ph: 'Số điện thoại *',
        prod_qty_ph: 'Số lượng',
        prod_city_ph: 'Tỉnh/thành nhận hàng',
        prod_note_ph: 'Ghi chú...',
        prod_confirm_btn: '✅ Xác Nhận Đặt Hàng',
        prod_call_btn: '📞 Gọi Ngay 0385.737.705',
        prod_success_msg: 'Đặt hàng "{title}" thành công! Admin/Mod sẽ liên hệ sớm.',
        prod_added_cart: 'Đã thêm "{title}" vào giỏ!',
        prod_deleted: 'Đã xoá!',

        // ── Order Page
        order_hero_title: '🛒 Order Taobao',
        order_hero_sub: 'Đặt hàng Trung Quốc giá gốc – Vận chuyển nhanh – An toàn',
        order_process_title: 'Quy Trình Đặt Hàng',
        order_s1_title: 'Chọn hàng Taobao',
        order_s1_desc: 'Tìm sản phẩm yêu thích trên app/web Taobao, sao chép link',
        order_s2_title: 'Gửi link cho HTM',
        order_s2_desc: 'Paste link vào form bên dưới hoặc gửi qua Zalo 0385.737.705',
        order_s3_title: 'Thanh toán & chờ hàng',
        order_s3_desc: 'HTM đặt hàng và vận chuyển về Việt Nam trong 7-10 ngày',
        order_s4_title: 'Nhận hàng tại nhà',
        order_s4_desc: 'Hàng được đóng gói cẩn thận, giao tận nơi toàn quốc',
        order_form_title: '📋 Gửi Yêu Cầu Đặt Hàng',
        order_name_ph: 'Họ và tên *',
        order_phone_ph: 'Số điện thoại *',
        order_link_ph: 'Link sản phẩm Taobao *',
        order_desc_ph: 'Tên / mô tả hàng',
        order_qty_ph: 'Số lượng',
        order_note_ph: 'Ghi chú (màu sắc, size, yêu cầu đặc biệt...)',
        order_submit_btn: '🚀 Gửi Đơn Hàng',
        order_call_btn: '📞 Gọi Tư Vấn 0385.737.705',
        order_price_title: '💰 Bảng Giá Vận Chuyển',
        price_weight: 'Cân nặng',
        price_domestic: '🇻🇳 Nội địa',
        price_china: '🇨🇳 Trung Quốc',
        guarantee1: 'Bảo hiểm hàng hóa 100%',
        guarantee2: 'Theo dõi đơn hàng realtime',
        guarantee3: 'Hoàn tiền nếu hàng lỗi',
        order_success_h: 'Đã Gửi Thành Công!',
        order_success_p: 'HTM sẽ liên hệ trong 30 phút qua số bạn cung cấp.',
        order_toast: '✅ Đã gửi đơn! Admin/Mod sẽ liên hệ xác nhận trong 30 phút.',

        // ── Contact Page
        contact_hero_title: '📞 Liên Hệ HTM Trường Hải',
        contact_hero_sub: 'Luôn sẵn sàng tư vấn và đồng hành cùng bạn',
        contact_hotline: 'Hotline',
        contact_hotline_val: '0385.737.705',
        contact_zalo: 'Zalo',
        contact_zalo_val: 'Chat ngay 0385.737.705',
        contact_addr: 'Địa chỉ',
        contact_addr_val: 'Hà Giang, Việt Nam',
        contact_hours: 'Giờ làm việc',
        contact_hours_val: '7:00 – 22:00 hằng ngày',
        contact_form_title: '💬 Gửi Yêu Cầu Tư Vấn',
        contact_name_ph: 'Họ và tên *',
        contact_phone_ph: 'Điện thoại *',
        contact_email_ph: 'Email (không bắt buộc)',
        contact_svc_ph: '-- Chọn chủ đề --',
        contact_svc1: 'Hỏi về bài viết',
        contact_svc2: 'Hợp tác / Quảng cáo',
        contact_svc3: 'Góp ý',
        contact_svc4: 'Khác',
        contact_msg_ph: 'Nội dung *',
        contact_submit_btn: '📨 Gửi',
        contact_call_btn: '📞 Gọi Ngay 0385.737.705',
        contact_sent_h: 'Đã Gửi Thành Công!',
        contact_sent_p: 'HTM Trường Hải sẽ liên hệ bạn sớm nhất có thể.',
        contact_send_more: 'Gửi Tiếp',
        contact_map_title: '📍 Vị Trí',
        contact_map1: '🏔️ Hà Giang – Vùng cực Bắc Tổ Quốc',
        contact_map2: '⏱️ Cách Hà Nội khoảng 300km (6-7 tiếng lái xe)',
        contact_map3: '✈️ Bay đến Nội Bài rồi đi xe về Hà Giang',
        contact_toast: '✅ Đã nhận yêu cầu! HTM sẽ phản hồi sớm.',

        // ── App modals
        login_title: 'Đăng Nhập',
        login_username_ph: 'Tên đăng nhập',
        login_password_ph: 'Mật khẩu',
        login_btn: 'Đăng Nhập',
        admin_add: '➕ Thêm',
        admin_type_post: 'Bài Viết',
        admin_title_ph: 'Tiêu đề bài viết',
        admin_content_ph: 'Nội dung bài viết',
        admin_author_ph: 'Tên tác giả',
        admin_img_label: 'Ảnh bài đăng',
        admin_img_click: 'Click để tải ảnh lên',
        admin_img_or: '— hoặc nhập URL ảnh —',
        admin_change_img: 'Đổi ảnh',
        admin_save_btn: '✅ Lưu',
        admin_success: '✅ Đã đăng {type} thành công!',
        footer_copy: '© 2026',

        // ── WhatsApp
        contact_whatsapp: 'WhatsApp',
        contact_whatsapp_val: 'Nhắn tin 0385.737.705',

        // ── Blog edit
        blog_edit: '✏️ Sửa',
        admin_update_btn: '✅ Cập nhật',
        admin_edit_title: 'Chỉnh sửa bài viết',

        // ── Misc
        price_contact: 'Liên hệ',
        delete_tooltip: 'Xoá',

        // ── Featured tours (HomePage)
        featured_t1: 'Tour Đồng Văn – Mã Pí Lèng',
        featured_t1_price: '2.500.000đ',
        featured_t2: 'Homestay Hoàng Su Phì',
        featured_t2_price: '800.000đ/đêm',
        featured_t3: 'Trekking Đỉnh Mây',
        featured_t3_price: '1.800.000đ',

        // ── Nav labels
        nav_du_an: '🌱 Dự Án',
        nav_thu_vien: '📚 Thư Viện',
        nav_kham_pha: '🗺️ Khám Phá Hà Giang',
        nav_san_pham: '🛍️ Sản Phẩm',

        // ── HomePage NGO
        hp_eyebrow: 'Tổ 5 Quang Trung · Phường Hà Giang 2 · Tuyên Quang',
        hp_h1_pre: 'Nơi', hp_h1_hl: '4 thế hệ', hp_h1_post: 'người dân tộc gìn giữ bản sắc',
        hp_hero_sub: '500m khỏi cửa ngõ Hà Giang Loop — workshop phụ nữ, thư viện số, du lịch bảo tồn cảnh quan',
        hp_hero_btn1: 'Khám phá dự án', hp_hero_btn2: 'Trở thành TNV',
        hp_story_badge: '~1000m · 500m khỏi Hà Giang Loop',
        hp_story_label: '📖 Câu chuyện của chúng tôi',
        hp_story_h2: 'Bốn thế hệ trên mảnh đất hoang sơ',
        hp_story_p1: 'Tổ 5 Quang Trung nằm trên sườn núi ~1.000m, cách mặt đường chính 500m — chỉ xe máy mới vào được. Vườn cây ăn quả trăm năm tuổi, gia đình người dân tộc 4 thế hệ, và một cộng đồng đang chủ động bước vào thời đại mới mà không đánh mất chính mình.',
        hp_story_p2: 'Trước làn sóng đô thị hoá, chúng tôi chọn trao quyền cho phụ nữ qua kỹ năng nghề và kỹ năng số, số hoá di sản trước khi nó biến mất, và mở cửa đón khách một cách có trách nhiệm.',
        hp_story_p2_em1: 'trao quyền cho phụ nữ', hp_story_p2_em2: 'số hoá di sản', hp_story_p2_em3: 'mở cửa đón khách',
        hp_story_btn: 'Tìm hiểu dự án đầy đủ',
        hp_prog_label: '🌱 Các chương trình', hp_prog_h2: 'Chúng tôi đang làm gì?',
        hp_prog1_title: 'Workshop Phụ Nữ', hp_prog1_desc: 'May, thêu thổ cẩm, kỹ năng số, tiếng Anh — miễn phí cho phụ nữ dân tộc.',
        hp_prog2_title: 'Thư Viện Số', hp_prog2_desc: 'Số hoá ngôn ngữ, văn hoá, ẩm thực dân tộc — bảo tồn cho thế hệ mai sau.',
        hp_prog3_title: 'Du Lịch Bảo Tồn', hp_prog3_desc: 'Trải nghiệm cuộc sống 4 thế hệ người dân tộc ngay cửa ngõ Hà Giang Loop.',
        hp_prog4_title: 'Tình Nguyện Viên', hp_prog4_desc: 'Góp tay cùng cộng đồng — dạy học, số hóa, phát triển du lịch bền vững.',
        hp_prog_cta: 'Tìm hiểu',
        hp_blog_label: '📝 Tin tức & Câu chuyện',
        hp_review_label: '💬 Cảm nhận', hp_review_h2: 'Du khách & cộng đồng nói gì?',
        hp_stat1: 'Phụ nữ được đào tạo', hp_stat2: 'Workshop / tháng',
        hp_stat3: 'Thế hệ cùng chung sống', hp_stat4: 'Du khách ghé thăm',
        hp_cta_label: 'Hành động ngay hôm nay',
        hp_cta_h2: 'Bạn có thể tạo ra sự khác biệt',
        hp_cta_sub: 'Dù là tình nguyện viên, du khách, hay người ủng hộ — mỗi sự tham gia đều có ý nghĩa.',
        hp_cta_btn1: 'Đăng ký tình nguyện', hp_cta_btn2: 'Tham gia workshop', hp_cta_btn3: 'Đặt tour bảo tồn',

        // ── CommunityPage
        comm_eyebrow: 'Tổ 5 Quang Trung · Phường Hà Giang 2 · Tuyên Quang',
        comm_h1a: 'Dự Án Cộng Đồng', comm_h1b: 'HTX Trường Hải',
        comm_hero_p: 'Trao quyền cho phụ nữ · Bảo tồn văn hoá · Phát triển bền vững — Ngay cửa ngõ Hà Giang Loop, ~1000m',
        comm_hero_btn1: 'Tham gia Workshop', comm_hero_btn2: 'Trở thành TNV',
        comm_stat1: 'Phụ nữ được đào tạo', comm_stat2: 'Workshop / tháng',
        comm_stat3: 'Du khách ghé thăm', comm_stat4: 'Thế hệ cùng chung sống',
        comm_stat5: 'Mục thư viện số', comm_stat6: 'Miễn phí cho phụ nữ',
        comm_story_label: '📖 Câu chuyện của chúng tôi',
        comm_story_h2: 'Bốn thế hệ trên mảnh đất cửa ngõ Hà Giang',
        comm_story_p1: 'Tổ 5 Quang Trung nằm trên sườn núi cao khoảng 1.000m, cách mặt đường chính 500m — chỉ xe máy mới vào được. Đây không phải bất lợi, mà là đặc ân: thiên nhiên hoang sơ, vườn cây ăn quả trăm năm tuổi, và gia đình người dân tộc 4 thế hệ vẫn còn đó.',
        comm_story_p2: 'Trước làn sóng đô thị hoá, chúng tôi chọn không đứng yên. Dự án ra đời để trao quyền cho phụ nữ qua kỹ năng nghề và kỹ năng số, số hoá di sản trước khi nó biến mất, và mở cửa đón khách một cách có trách nhiệm.',
        comm_story_btn: 'Khám phá địa điểm',
        comm_ms1_year: '~1940s', comm_ms1: 'Thế hệ thứ nhất định cư tại Tổ 5 Quang Trung, khai phá vườn cây ăn quả trên núi.',
        comm_ms2_year: '~1970s', comm_ms2: 'Thế hệ thứ hai mở rộng canh tác, gìn giữ nghề thêu thổ cẩm truyền thống.',
        comm_ms3_year: '2000s', comm_ms3: 'Thế hệ thứ ba chứng kiến đô thị hoá — cân bằng giữa hiện đại và bản sắc.',
        comm_ms4_year: '2024', comm_ms4: 'Thế hệ thứ tư khởi động dự án — kết nối cộng đồng, đào tạo phụ nữ, mở cửa đón khách.',
        comm_prog_label: '🌱 Các chương trình', comm_prog_h2: 'Chúng tôi đang làm gì?',
        comm_prog1_title: 'Workshop Phụ Nữ', comm_prog1_desc: 'Dạy may, thêu thổ cẩm, kỹ năng số và tiếng Anh giao tiếp miễn phí cho phụ nữ dân tộc.', comm_prog1_tag: 'Đang tuyển sinh',
        comm_prog2_title: 'Thư Viện Số', comm_prog2_desc: 'Số hoá ngôn ngữ, văn hóa, ẩm thực các dân tộc thiểu số — lưu giữ cho thế hệ mai sau.', comm_prog2_tag: 'Mở cửa',
        comm_prog3_title: 'Du Lịch Bảo Tồn', comm_prog3_desc: 'Trải nghiệm cuộc sống 4 thế hệ người dân tộc, cây ăn quả, cảnh quan hoang sơ cửa ngõ Hà Giang Loop.', comm_prog3_tag: 'Đặt lịch',
        comm_prog4_title: 'Tình Nguyện Viên', comm_prog4_desc: 'Góp tay cùng cộng đồng — dạy học, làm vườn, số hóa tư liệu, phát triển du lịch bền vững.', comm_prog4_tag: 'Tham gia',
        comm_prog_link: 'Tìm hiểu thêm',
        comm_cta_h2: 'Bạn có thể đóng góp gì?',
        comm_cta_p: 'Dù là tình nguyện viên, du khách, hay nhà hảo tâm — mỗi sự tham gia đều có ý nghĩa.',
        comm_cta_btn1: 'Đăng ký tình nguyện', comm_cta_btn2: 'Tham gia workshop', comm_cta_btn3: 'Đặt tour bảo tồn',

        // ── WorkshopPage
        ws_h1: 'Workshop Cộng Đồng',
        ws_sub: 'Miễn phí · Thực hành · Dành cho phụ nữ dân tộc & người học tiếng Anh',
        ws_info1: '📍 Địa điểm: Tổ 5 Quang Trung, Phường Hà Giang 2 (chỉ xe máy)',
        ws_info2: '🆓 Học phí: Miễn phí hoàn toàn',
        ws_info3: '📱 Liên hệ: 0385.737.705',
        ws_filter_all: '🌟 Tất cả', ws_cat_sewing: '🪡 May', ws_cat_embroidery: '🌸 Thêu',
        ws_cat_english: '🗣️ Tiếng Anh', ws_cat_digital: '💻 Kỹ năng số', ws_cat_cooking: '🍲 Ẩm thực',
        ws_full: 'Đã đủ chỗ', ws_reg_btn: 'Đăng ký tham gia', ws_empty: 'Không có workshop nào.',
        ws_registered: 'người đăng ký',
        ws_reg_title: '🎓 Đăng ký Workshop',
        ws_reg_success_h: 'Đăng ký thành công!',
        ws_reg_success_p: 'Chúng tôi sẽ liên hệ với bạn trước ngày diễn ra workshop.',
        ws_reg_close: 'Đóng', ws_reg_free: 'MIỄN PHÍ',
        ws_reg_name_ph: 'Họ và tên *', ws_reg_phone_ph: 'Số điện thoại *',
        ws_reg_email_ph: 'Email (không bắt buộc)',
        ws_reg_note_ph: 'Ghi chú (bạn muốn học gì, kinh nghiệm trước...)',
        ws_reg_confirm: 'Xác nhận đăng ký',

        // ── LibraryPage
        lib_h1: 'Thư Viện Số',
        lib_sub: 'Ngôn ngữ · Ẩm thực · Văn hoá · Nghề thủ công — di sản dân tộc được lưu giữ',
        lib_search_ph: 'Tìm kiếm tư liệu...',
        lib_filter_all: '🌐 Tất cả', lib_count_unit: 'tư liệu',
        lib_empty: 'Không tìm thấy tư liệu nào.', lib_expand: 'Xem thêm ▼', lib_collapse: 'Thu gọn ▲',
        cat_language: 'Ngôn ngữ', cat_food: 'Ẩm thực', cat_culture: 'Văn hoá',
        cat_craft: 'Nghề thủ công', cat_nature: 'Thiên nhiên', cat_story: 'Câu chuyện',

        // ── VolunteerPage
        vol_h1: 'Trở Thành Tình Nguyện Viên',
        vol_sub: 'Góp tay bảo tồn văn hoá · Dạy học · Phát triển cộng đồng bền vững',
        vol_section_label: '🙋 Chúng tôi cần bạn', vol_h2: 'Bạn có thể đóng góp gì?',
        vol_intro: 'Dự án luôn chào đón tình nguyện viên — không cần kinh nghiệm, chỉ cần nhiệt huyết. Bạn có thể ở lại vài ngày, vài tuần, hoặc đóng góp từ xa.',
        vol_logistics_h: 'Thông tin thực tế',
        vol_testimonials_h: 'TNV nói gì?',
        vol_done_h: 'Cảm ơn bạn!',
        vol_done_p: 'Chúng tôi sẽ liên hệ với bạn trong vòng 24–48 giờ để trao đổi chi tiết.',
        vol_done_btn: 'Gửi thêm đơn khác',
        vol_form_h: '📋 Đơn Tình Nguyện', vol_form_p: 'Điền thông tin bên dưới — chúng tôi sẽ liên hệ trong 24h.',
        vol_name_ph: 'Họ và tên *', vol_phone_ph: 'Số điện thoại', vol_email_ph: 'Email',
        vol_skills_ph: 'Kỹ năng bạn muốn đóng góp *',
        vol_avail_ph: 'Thời gian có thể tham gia (VD: 2 tuần tháng 6)',
        vol_motivation_ph: 'Bạn muốn đóng góp điều gì cho cộng đồng? *',
        vol_submit_btn: 'Gửi đơn tình nguyện', vol_call_btn: '📞 Gọi trực tiếp: 0385.737.705',
        vol_skill1: '📚 Dạy học (tiếng Anh, kỹ năng số)', vol_skill2: '🌱 Nông nghiệp & làm vườn',
        vol_skill3: '📷 Nhiếp ảnh / quay phim', vol_skill4: '🔨 Xây dựng / sửa chữa',
        vol_skill5: '💻 Công nghệ / số hoá tư liệu', vol_skill6: '✨ Kỹ năng khác',

        // ── DiscoverPage
        dc_badge: '🌏 Cực Bắc Việt Nam · Tuyên Quang',
        dc_hero_t1: 'Hộ Chiếu', dc_hero_t2: 'Trải Nghiệm', dc_hero_t3: 'Hà Giang',
        dc_hero_sub: 'Khám phá, trải nghiệm, và mang về chứng nhận số\ntừ miền núi đá hùng vĩ nhất Việt Nam',
        dc_btn_start: '🌸 Bắt đầu hành trình', dc_btn_tours: '🏍️ Xem tour',
        dc_stamp_bar_pre: '✅ Bạn đã có', dc_stamp_bar_mid: 'tem', dc_stamp_bar_post: '→ Xem ngay',
        dc_pp_holder: 'THÔNG TIN NGƯỜI CẦM',
        dc_pp_name_field: 'Họ tên', dc_pp_stamps_field: 'Tem đã có', dc_pp_stamps_unit: 'tem',
        dc_pp_no_passport: '✈️ Chưa có hộ chiếu', dc_pp_no_passport2: 'Bắt đầu hành trình ngay!',
        dc_pp_open: '📖 Mở hộ chiếu', dc_pp_create: '🌸 Tạo hộ chiếu',
        dc_collect_title: 'Thu thập tem · Nhận chứng nhận',
        dc_collect_desc: 'Mỗi trải nghiệm tại HTX Trường Hải tặng bạn một con tem số. Thu thập đủ tem để xuất Chứng nhận Trải nghiệm Hà Giang — tặng bạn bè, chia sẻ mạng xã hội, hay giữ làm kỷ niệm.',
        dc_got: '✓ Đã có', dc_no_stamp: 'Chưa có tem',
        dc_btn_start_now: 'Bắt đầu ngay',
        dc_exp_title: 'Trải nghiệm Hà Giang', dc_exp_sub: 'Mỗi hoạt động giúp bạn kiếm thêm tem cho hộ chiếu',
        dc_tours_open: 'tour đang mở', dc_prods_avail: 'sản phẩm',
        dc_stamp_earned: '🎖️ Đã có tem',
        dc_bw_title: 'Hoa tam giác mạch nở rộ · Tháng 10–12',
        dc_bw_sub: 'Đến Hà Giang mùa hoa và mang về chứng nhận trải nghiệm đặc biệt nhất',
        dc_bw_btn: '🗺️ Tạo hộ chiếu của bạn →',
        dc_hl1: 'Cao nguyên Đồng Văn', dc_hl1s: 'Di sản địa chất UNESCO',
        dc_hl2: 'Đèo Mã Pí Lèng', dc_hl2s: 'Đệ nhất hùng quan',
        dc_hl3: 'Hoa Tam giác mạch', dc_hl3s: 'Tháng 10–12 hàng năm',
        dc_hl4: 'Bản sắc dân tộc', dc_hl4s: "H'Mông, Dao, Lô Lô...",
        dc_exp1t: 'Tour & Phượt', dc_exp1d: 'Loop Rider, trekking, homestay dân tộc',
        dc_exp2t: 'Thủ công mỹ nghệ', dc_exp2d: 'Thêu, dệt, trang phục dân tộc chính hãng',
        dc_exp3t: 'Đào tạo miễn phí', dc_exp3d: 'EasyRider, tiếng Anh, quay video, trang điểm',
        dc_exp4t: 'Hỗ trợ cộng đồng', dc_exp4d: 'Du khách nữ · Lao động · Đài phát thanh',

        // ── PassportPage
        pp_back: '← Trang khám phá',
        pp_cover_country: 'CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM',
        pp_cover_title1: 'HỘ CHIếU', pp_cover_title2: 'TRẢI NGHIỆM',
        pp_cover_org: 'HTX Trường Hải · Tuyên Quang',
        pp_dp_title: '📋 THÔNG TIN NGƯỜI DÙNG',
        pp_name_ph: 'Nhập tên của bạn...', pp_save: 'Lưu',
        pp_dp_issued: 'Cấp bởi', pp_dp_created: 'Ngày tạo', pp_dp_stamps: 'Tem cơ bản',
        pp_progress_done: '🎉 Hoàn thành tất cả tem!', pp_progress_pct: '% hành trình cơ bản',
        pp_cert_spec: 'Chứng nhận đặc biệt',
        pp_no_name_hint: '💡 Nhập tên của bạn ở trái để nhận tem đầu tiên 🌸',
        pp_tab_basic: 'Tem cơ bản',
        pp_basic_title: '🎖️ Bộ sưu tập tem cơ bản',
        pp_howto_title: 'Cách kiếm tem',
        pp_cert_title_basic: '🏆 Chứng nhận Trải nghiệm',
        pp_cert_no_stamps: 'Hãy kiếm ít nhất 1 tem để xuất chứng nhận.',
        pp_cert_has: 'Bạn có {n} tem. Tải xuống chứng nhận PNG.',
        pp_cert_dl: 'Tải PNG',
        pp_ct_need: 'Cần {min}/{total} địa danh để nhận chứng nhận',
        pp_ct_enough: '🎉 Đủ điều kiện nhận chứng nhận!',
        pp_ct_more: 'Còn {n} tem nữa để nhận chứng nhận.',
        pp_ct_cert_ready: 'Xuất chứng nhận của bạn dưới dạng ảnh PNG.',
        pp_ct_cert_locked: 'Cần thêm {n} địa danh nữa.',
        pp_ct_name_req: 'Nhập tên trước',
        pp_ct_downloaded: '✅ Đã tải!', pp_ct_dl: 'Tải PNG',
        pp_ct_claim: 'Tôi đã đến! ✓',
        pp_rev_title: '📝 Đánh giá trải nghiệm',
        pp_rev_rating_label: 'Đánh giá của bạn',
        pp_rev_loc_ph: 'Địa danh / hoạt động bạn đã trải nghiệm...',
        pp_rev_comment_ph: 'Chia sẻ cảm nhận của bạn về trải nghiệm tại Hà Giang...',
        pp_rev_submit: 'Gửii đánh giá',
        pp_rev_sent: '✅ Cảm ơn bạn đã chia sẻ! Đánh giá đã được lưu.',

        // ── WomenSupportPage
        ws_hero_title: '💜 Hỗ trợ Phụ nữ & Cộng đồng',
        ws_hero_sub: 'Không ai phải đối mặt một mình — Chúng tôi ở đây, lắng nghe và đồng hành',
        ws_emergency_label: 'Dường dây khẩn cấp — Miễn phí 24/7:',
        ws_our_services: 'Các hỗ trợ của chúng tôi',
        ws_what_help: 'Chúng tôi có thể giúp gì',
        ws_urgent_badge: 'Khẩn cấp — Gọi ngay 1800 599 920',
        ws_contact_btn: 'Liên hệ hỗ trợ',
        ws_modal_confidential: 'Thông tin của bạn được bảo mật tuyệt đối',
        ws_urgent_banner_pre: '🆘 Khẩn cấp? Gọi ngay',
        ws_urgent_banner_post: '(miễn phí, 24/7)',
        ws_anonymous: '🎭 Liên hệ ẩn danh',
        ws_name_ph: 'Tên của bạn',
        ws_phone_ph: 'Số điện thoại (để chúng tôi gọi lại)',
        ws_msg_ph: 'Mô tả tình huống của bạn… (bảo mật hoàn toàn)',
        ws_send_btn: 'Gửii yêu cầu hỗ trợ',
        ws_sent_title: 'Tin nhắn đã gửii thành công',
        ws_sent_sub: 'Đội hỗ trợ HTX Trường Hải sẽ liên hệ bạn trong vòng 2–4 giờ.',
        ws_sent_urgent: '🆘 Nếu khẩn cấp: gọi ngay 1800 599 920 (miễn phí)',
        ws_close: 'Đóng',
        ws_radio_title: 'Đài phát thanh cộng đồng',
        ws_radio_sub: 'Một không gian ấm áp để chia sẻ câu chuyện cuộc sống — tình yêu, gia đình, vượt khó.',
        ws_schedule_tab: '📅 Lịch phát sóng',
        ws_listen_tab: 'Nghe trực tuyến',
        ws_radio_tagline: 'Phát sóng mỗi tối — Lắng nghe & Đồng hành',
        ws_on_air: 'Đang phát:',
        ws_off_air: '📅 Xem lịch phát sóng',
        ws_play_hint: 'Nhấn nút ↓ để nghe đài',
        ws_stream_hint: '💡 Phát sóng theo lịch. Kiểm tra tab Lịch phát sóng nếu không có tín hiệu.',
    },

    en: {
        // ── Navigation
        nav_home: '🏠 Home',
        nav_blog: '📝 Blog',
        nav_contact: '📞 Contact',
        btn_login: 'Login',
        btn_logout: 'Sign Out',

        // ── Nav labels
        nav_du_an: '🌱 Projects',
        nav_thu_vien: '📚 Library',
        nav_kham_pha: '🗺️ Discover Ha Giang',
        nav_san_pham: '🛍️ Products',

        // ── Tours Hero
        tours_hero_title: '🗺️ Discover Ha Giang',
        blog_hero_title: '📝 Blog',
        blog_hero_sub: 'Stories, experiences and insights shared by HTM Truong Hai',
        blog_search: 'Search articles...',
        blog_add: 'New Post',
        blog_back: '← Back to Blog',
        blog_read_more: 'Read More »',
        blog_empty: 'No posts yet 📝',
        blog_deleted: 'Deleted!',
        tours_hero_sub: 'Terraced Rice Fields · Mã Pí Lèng Peak · Dong Van Stone Plateau',
        tours_search: 'Search...',
        tours_add: '+ Add New',
        tours_no_result: 'Not found 😢',
        tours_filter_all: 'All',
        tours_filter_budget: '💰 Budget',
        tours_filter_premium: '⭐ Premium',
        tours_filter_trek: '🥾 Trekking',
        tours_sort: 'Sort',
        tours_sort_default: 'Default',
        tours_sort_price_asc: 'Price: Low → High',
        tours_sort_price_desc: 'Price: High → Low',
        tours_sort_rating: 'Top Rated',
        tours_results: 'discover',

        // ── Tour Card
        card_from: 'From',
        card_per_person: '/person',
        card_duration: 'Duration',
        card_max: 'Max',
        card_people: 'people',
        card_rating: 'Rating',
        card_detail: 'View Details',
        card_book: '🗓 Book Now',
        card_includes: 'Includes:',

        // ── Includes labels
        inc_transport: '🚌 Transport',
        inc_meal: '🍽️ Meals',
        inc_guide: '🧭 Tour Guide',
        inc_hotel: '🏨 Accommodation',
        inc_ticket: '🎫 Entry Tickets',

        // ── Booking Modal
        book_title: '🗺️ Book',
        book_step1: 'Date',
        book_step2: 'Your Info',
        book_step3: 'Confirm',
        book_departure_date: 'Departure Date *',
        book_guest_count: 'Number of Guests',
        book_adults: 'Adults',
        book_children: 'Children',
        book_next: 'Next →',
        book_full_name: 'Full Name *',
        book_phone: 'Phone Number *',
        book_email: 'Email (optional)',
        book_notes: 'Special Requests',
        book_notes_ph: 'Food allergies, private room, special requirements...',
        book_back: '← Back',
        book_summary_title: '📋 Booking Summary',
        book_tour_label: 'Discover',
        book_date_label: 'Departure Date',
        book_total_guests: 'Total Guests',
        book_price_per: 'Price / person',
        book_contact_label: 'Contact',
        book_note_label: 'Notes',
        book_confirm: '✅ Confirm Booking',
        book_call: '📞 Call 0385.737.705',
        book_no_date: '⚠️ Please select a departure date',
        book_required_msg: '⚠️ Please fill in all required fields',
        book_success_msg: '"{title}" booked! Admin/Mod will contact you soon.',
        book_adults_label: 'adults',
        book_children_label: 'children',
        book_and: 'and',
        book_deleted: 'Deleted!',

        // ── Home Page
        hero_badge: '📝 Blog & Sharing',
        hero_h1_blog: 'Blog by',
        hero_blog_name: 'HTM Truong Hai',
        hero_sub: 'Sharing experiences, stories and interesting things every day.',
        hero_btn_blog: '📝 Read Blog',
        hero_btn_contact: '📞 Contact',
        home_recent_posts: 'Latest Posts',
        home_see_all: 'View all',
        cta_title: 'Get in Touch',
        cta_sub: 'Have a question or want to collaborate? Contact HTM Truong Hai today.',
        cta_call: '📞 Call 0385.737.705',
        cta_consult: '📋 Send Request',
        logo_sub: 'Blog & Sharing',

        // ── Products Page
        prod_hero_title: '🍯 Ha Giang Specialties',
        prod_hero_sub: 'Pure highland products, carefully selected from local farmers',
        prod_search: 'Search products...',
        prod_add: 'Add Product',
        prod_no_result: 'No products found 😢',
        prod_badge: '🌿 Natural',
        prod_detail: 'Details',
        prod_cart: 'Cart',
        prod_buy: 'Buy',
        prod_order_title: '🛒 Purchase',
        prod_name_ph: 'Full Name *',
        prod_phone_ph: 'Phone Number *',
        prod_qty_ph: 'Quantity',
        prod_city_ph: 'Delivery city/province',
        prod_note_ph: 'Notes...',
        prod_confirm_btn: '✅ Confirm Order',
        prod_call_btn: '📞 Call 0385.737.705',
        prod_success_msg: 'Order for "{title}" placed! Admin/Mod will contact you soon.',
        prod_added_cart: '"{title}" added to cart!',
        prod_deleted: 'Deleted!',

        // ── Order Page
        order_hero_title: '🛒 Taobao Order',
        order_hero_sub: 'Chinese products at factory price – Fast shipping – Safe',
        order_process_title: 'Ordering Process',
        order_s1_title: 'Choose Taobao Products',
        order_s1_desc: 'Find your favorite products on the Taobao app/website, copy the link',
        order_s2_title: 'Send Link to HTM',
        order_s2_desc: 'Paste the link into the form below or send via Zalo 0385.737.705',
        order_s3_title: 'Pay & Wait for Delivery',
        order_s3_desc: 'HTM places the order and ships to Vietnam within 7-10 days',
        order_s4_title: 'Receive at Home',
        order_s4_desc: 'Goods are carefully packed and delivered nationwide',
        order_form_title: '📋 Submit Order Request',
        order_name_ph: 'Full Name *',
        order_phone_ph: 'Phone Number *',
        order_link_ph: 'Taobao product link *',
        order_desc_ph: 'Product name/description',
        order_qty_ph: 'Quantity',
        order_note_ph: 'Notes (color, size, special requirements...)',
        order_submit_btn: '🚀 Submit Order',
        order_call_btn: '📞 Call for Advice 0385.737.705',
        order_price_title: '💰 Shipping Price Table',
        price_weight: 'Weight',
        price_domestic: '🇻🇳 Domestic',
        price_china: '🇨🇳 From China',
        guarantee1: '100% Goods Insurance',
        guarantee2: 'Real-time order tracking',
        guarantee3: 'Refund if goods are defective',
        order_success_h: 'Successfully Sent!',
        order_success_p: 'HTM will contact you within 30 minutes.',
        order_toast: '✅ Order sent! Admin/Mod will confirm within 30 minutes.',

        // ── Contact Page
        contact_hero_title: '📞 Contact HTM Truong Hai',
        contact_hero_sub: 'Always ready to assist and accompany you',
        contact_hotline: 'Hotline',
        contact_hotline_val: '0385.737.705',
        contact_zalo: 'Zalo',
        contact_zalo_val: 'Chat now 0385.737.705',
        contact_addr: 'Address',
        contact_addr_val: 'Ha Giang, Vietnam',
        contact_hours: 'Working Hours',
        contact_hours_val: '7:00 AM – 10:00 PM Daily',
        contact_form_title: '💬 Send a Message',
        contact_name_ph: 'Full Name *',
        contact_phone_ph: 'Phone *',
        contact_email_ph: 'Email (optional)',
        contact_svc_ph: '-- Select topic --',
        contact_svc1: 'Question about a post',
        contact_svc2: 'Collaboration / Advertising',
        contact_svc3: 'Feedback',
        contact_svc4: 'Other',
        contact_msg_ph: 'Message *',
        contact_submit_btn: '📨 Send',
        contact_call_btn: '📞 Call 0385.737.705',
        contact_sent_h: 'Successfully Sent!',
        contact_sent_p: 'HTM Truong Hai will get back to you as soon as possible.',
        contact_send_more: 'Send Another',
        contact_map_title: '📍 Location',
        contact_map1: '🏔️ Ha Giang – Northernmost Region of Vietnam',
        contact_map2: '⏱️ About 300km from Hanoi (6-7 hours drive)',
        contact_map3: '✈️ Fly to Noi Bai airport then drive to Ha Giang',
        contact_toast: '✅ Message received! HTM will respond soon.',

        // ── App modals
        login_title: 'Sign In',
        login_username_ph: 'Username',
        login_password_ph: 'Password',
        login_btn: 'Sign In',
        admin_add: '➕ Add',
        admin_type_post: 'Blog Post',
        admin_title_ph: 'Post title',
        admin_content_ph: 'Post content',
        admin_author_ph: 'Author name',
        admin_img_label: 'Post image',
        admin_img_click: 'Click to upload image',
        admin_img_or: '— or enter image URL —',
        admin_change_img: 'Change image',
        admin_save_btn: '✅ Save',
        admin_success: '✅ Successfully published {type}!',
        footer_copy: '© 2026',

        // ── WhatsApp
        contact_whatsapp: 'WhatsApp',
        contact_whatsapp_val: 'Message 0385.737.705',

        // ── Blog edit
        blog_edit: '✏️ Edit',
        admin_update_btn: '✅ Update',
        admin_edit_title: 'Edit Post',

        // ── Misc
        price_contact: 'Contact us',
        delete_tooltip: 'Delete',

        // ── HomePage NGO
        hp_eyebrow: 'Commune 5, Quang Trung · Phuong Ha Giang 2 · Tuyen Quang',
        hp_h1_pre: 'Where', hp_h1_hl: '4 generations', hp_h1_post: 'of ethnic people preserve their heritage',
        hp_hero_sub: '500m from the gate of Ha Giang Loop — women\'s workshops, digital library, conservation tourism',
        hp_hero_btn1: 'Explore projects', hp_hero_btn2: 'Become a volunteer',
        hp_story_badge: '~1000m · 500m from Ha Giang Loop',
        hp_story_label: '📖 Our Story',
        hp_story_h2: 'Four generations on wild mountain land',
        hp_story_p1: 'Commune 5 Quang Trung sits on a mountain slope at ~1,000m, accessible only by motorbike. A century-old fruit garden, a 4-generation ethnic family, and a community actively stepping into the modern era without losing themselves.',
        hp_story_p2: 'Facing urbanization, we chose to empower women through vocational and digital skills, digitize heritage before it disappears, and open our doors to guests responsibly.',
        hp_story_p2_em1: 'empower women', hp_story_p2_em2: 'digitize heritage', hp_story_p2_em3: 'open our doors',
        hp_story_btn: 'Learn more about the project',
        hp_prog_label: '🌱 Our Programs', hp_prog_h2: 'What we\'re doing',
        hp_prog1_title: 'Women\'s Workshop', hp_prog1_desc: 'Sewing, embroidery, digital skills, English — free for ethnic minority women.',
        hp_prog2_title: 'Digital Library', hp_prog2_desc: 'Digitizing languages, culture, and cuisine of ethnic minorities — preserving for future generations.',
        hp_prog3_title: 'Conservation Tourism', hp_prog3_desc: 'Experience 4 generations of ethnic life at the gateway of Ha Giang Loop.',
        hp_prog4_title: 'Volunteers', hp_prog4_desc: 'Join the community — teaching, digitizing, developing sustainable tourism.',
        hp_prog_cta: 'Learn more',
        hp_blog_label: '📝 News & Stories',
        hp_review_label: '💬 Feedback', hp_review_h2: 'What visitors & community say',
        hp_stat1: 'Women trained', hp_stat2: 'Workshops / month',
        hp_stat3: 'Generations together', hp_stat4: 'Visitors welcomed',
        hp_cta_label: 'Take action today',
        hp_cta_h2: 'You can make a difference',
        hp_cta_sub: 'Whether as a volunteer, visitor, or supporter — every participation matters.',
        hp_cta_btn1: 'Sign up to volunteer', hp_cta_btn2: 'Join a workshop', hp_cta_btn3: 'Book conservation tour',

        // ── CommunityPage
        comm_eyebrow: 'Commune 5, Quang Trung · Phuong Ha Giang 2 · Tuyen Quang',
        comm_h1a: 'Community Project', comm_h1b: 'HTX Truong Hai',
        comm_hero_p: 'Empowering women · Preserving culture · Sustainable development — At the gateway of Ha Giang Loop, ~1000m',
        comm_hero_btn1: 'Join Workshop', comm_hero_btn2: 'Become a Volunteer',
        comm_stat1: 'Women trained', comm_stat2: 'Workshops / month',
        comm_stat3: 'Visitors welcomed', comm_stat4: 'Generations together',
        comm_stat5: 'Digital library items', comm_stat6: 'Free for women',
        comm_story_label: '📖 Our Story',
        comm_story_h2: 'Four generations at the gateway of Ha Giang',
        comm_story_p1: 'Commune 5 Quang Trung sits on a mountain slope at ~1,000m, accessible only by motorbike. This is not a disadvantage but a gift: wild nature, a century-old fruit garden, and a 4-generation ethnic family still intact.',
        comm_story_p2: 'Facing urbanization, we chose not to stand still. The project was born to empower women through vocational and digital skills, digitize heritage before it disappears, and open doors to guests responsibly.',
        comm_story_btn: 'Explore the location',
        comm_ms1_year: '~1940s', comm_ms1: 'First generation settled in Commune 5, cultivating a mountain fruit garden.',
        comm_ms2_year: '~1970s', comm_ms2: 'Second generation expanded farming, preserving traditional brocade embroidery.',
        comm_ms3_year: '2000s', comm_ms3: 'Third generation witnessed urbanization — balancing modernity and cultural identity.',
        comm_ms4_year: '2024', comm_ms4: 'Fourth generation launched the project — connecting community, training women, welcoming visitors.',
        comm_prog_label: '🌱 Our Programs', comm_prog_h2: 'What we\'re doing',
        comm_prog1_title: 'Women\'s Workshop', comm_prog1_desc: 'Free sewing, brocade embroidery, digital skills and English for ethnic minority women.', comm_prog1_tag: 'Now enrolling',
        comm_prog2_title: 'Digital Library', comm_prog2_desc: 'Digitizing languages, culture, cuisine of ethnic minorities — preserved for future generations.', comm_prog2_tag: 'Open',
        comm_prog3_title: 'Conservation Tourism', comm_prog3_desc: 'Experience 4 generations of ethnic life, fruit gardens, and wild landscapes at the Ha Giang Loop gateway.', comm_prog3_tag: 'Book now',
        comm_prog4_title: 'Volunteers', comm_prog4_desc: 'Join the community — teaching, gardening, digitizing archives, developing sustainable tourism.', comm_prog4_tag: 'Join',
        comm_prog_link: 'Learn more',
        comm_cta_h2: 'How can you contribute?',
        comm_cta_p: 'Whether as a volunteer, visitor, or donor — every participation matters.',
        comm_cta_btn1: 'Sign up to volunteer', comm_cta_btn2: 'Join a workshop', comm_cta_btn3: 'Book conservation tour',

        // ── WorkshopPage
        ws_h1: 'Community Workshop',
        ws_sub: 'Free · Hands-on · For ethnic minority women & English learners',
        ws_info1: '📍 Location: Commune 5, Quang Trung, Phuong Ha Giang 2 (motorbike access only)',
        ws_info2: '🆓 Tuition: Completely free',
        ws_info3: '📱 Contact: 0385.737.705',
        ws_filter_all: '🌟 All', ws_cat_sewing: '🪡 Sewing', ws_cat_embroidery: '🌸 Embroidery',
        ws_cat_english: '🗣️ English', ws_cat_digital: '💻 Digital Skills', ws_cat_cooking: '🍲 Ethnic Cuisine',
        ws_full: 'Full', ws_reg_btn: 'Register', ws_empty: 'No workshops available.',
        ws_registered: 'registered',
        ws_reg_title: '🎓 Register for Workshop',
        ws_reg_success_h: 'Registration Successful!',
        ws_reg_success_p: 'We will contact you before the workshop date.',
        ws_reg_close: 'Close', ws_reg_free: 'FREE',
        ws_reg_name_ph: 'Full name *', ws_reg_phone_ph: 'Phone number *',
        ws_reg_email_ph: 'Email (optional)',
        ws_reg_note_ph: 'Notes (what you want to learn, prior experience...)',
        ws_reg_confirm: 'Confirm Registration',

        // ── LibraryPage
        lib_h1: 'Digital Library',
        lib_sub: 'Language · Cuisine · Culture · Crafts — ethnic heritage preserved',
        lib_search_ph: 'Search archives...',
        lib_filter_all: '🌐 All', lib_count_unit: 'items',
        lib_empty: 'No items found.', lib_expand: 'Show more ▼', lib_collapse: 'Collapse ▲',
        cat_language: 'Language', cat_food: 'Cuisine', cat_culture: 'Culture',
        cat_craft: 'Crafts', cat_nature: 'Nature', cat_story: 'Stories',

        // ── VolunteerPage
        vol_h1: 'Become a Volunteer',
        vol_sub: 'Help preserve culture · Teach · Develop sustainable community',
        vol_section_label: '🙋 We need you', vol_h2: 'How can you contribute?',
        vol_intro: 'The project always welcomes volunteers — no experience needed, just enthusiasm. You can stay for a few days, a few weeks, or contribute remotely.',
        vol_logistics_h: 'Practical Info',
        vol_testimonials_h: 'What volunteers say',
        vol_done_h: 'Thank you!',
        vol_done_p: 'We will contact you within 24–48 hours to discuss details.',
        vol_done_btn: 'Submit another application',
        vol_form_h: '📋 Volunteer Application', vol_form_p: 'Fill in the form below — we\'ll get back to you within 24h.',
        vol_name_ph: 'Full name *', vol_phone_ph: 'Phone number', vol_email_ph: 'Email',
        vol_skills_ph: 'Skills you want to contribute *',
        vol_avail_ph: 'Available dates (e.g. 2 weeks in June)',
        vol_motivation_ph: 'What would you like to contribute to the community? *',
        vol_submit_btn: 'Submit application', vol_call_btn: '📞 Call directly: 0385.737.705',
        vol_skill1: '📚 Teaching (English, digital skills)', vol_skill2: '🌱 Agriculture & gardening',
        vol_skill3: '📷 Photography / videography', vol_skill4: '🔨 Construction / repairs',
        vol_skill5: '💻 Technology / archive digitization', vol_skill6: '✨ Other skills',

        // ── DiscoverPage
        dc_badge: '🌏 Northernmost Vietnam · Tuyen Quang',
        dc_hero_t1: 'Experience', dc_hero_t2: 'Passport', dc_hero_t3: 'Ha Giang',
        dc_hero_sub: 'Explore, experience, and bring home a digital certificate\nfrom Vietnam\'s most majestic limestone plateau',
        dc_btn_start: '🌸 Start Your Journey', dc_btn_tours: '🏍️ View Tours',
        dc_stamp_bar_pre: '✅ You have', dc_stamp_bar_mid: 'stamps', dc_stamp_bar_post: '→ View now',
        dc_pp_holder: 'HOLDER INFORMATION',
        dc_pp_name_field: 'Name', dc_pp_stamps_field: 'Stamps', dc_pp_stamps_unit: 'stamps',
        dc_pp_no_passport: '✈️ No passport yet', dc_pp_no_passport2: 'Start your journey now!',
        dc_pp_open: '📖 Open Passport', dc_pp_create: '🌸 Create Passport',
        dc_collect_title: 'Collect Stamps · Get Certified',
        dc_collect_desc: 'Every experience at HTX Truong Hai earns you a digital stamp. Collect enough to download your Ha Giang Experience Certificate — share it, gift it, or keep it as a memory.',
        dc_got: '✓ Earned', dc_no_stamp: 'No stamps yet',
        dc_btn_start_now: 'Get Started',
        dc_exp_title: 'Ha Giang Experiences', dc_exp_sub: 'Each activity earns you stamps for your passport',
        dc_tours_open: 'tours available', dc_prods_avail: 'products',
        dc_stamp_earned: '🎖️ Stamp earned',
        dc_bw_title: 'Buckwheat flowers in bloom · Oct–Dec',
        dc_bw_sub: 'Visit Ha Giang in bloom season and bring back the most special experience certificate',
        dc_bw_btn: '🗺️ Create your passport →',
        dc_hl1: 'Dong Van Plateau', dc_hl1s: 'UNESCO Geopark Heritage',
        dc_hl2: 'Ma Pi Leng Pass', dc_hl2s: "Vietnam's grandest pass",
        dc_hl3: 'Buckwheat Flowers', dc_hl3s: 'October–December yearly',
        dc_hl4: 'Ethnic Heritage', dc_hl4s: "H'Mong, Dao, Lo Lo...",
        dc_exp1t: 'Tours & Rides', dc_exp1d: 'Loop Rider, trekking, ethnic homestay',
        dc_exp2t: 'Handicrafts', dc_exp2d: 'Embroidery, weaving, authentic ethnic clothing',
        dc_exp3t: 'Free Training', dc_exp3d: 'EasyRider, English, video production, makeup',
        dc_exp4t: 'Community Support', dc_exp4d: 'Women travelers · Workers · Radio',

        // ── PassportPage
        pp_back: '← Explore',
        pp_cover_country: 'SOCIALIST REPUBLIC OF VIETNAM',
        pp_cover_title1: 'EXPERIENCE', pp_cover_title2: 'PASSPORT',
        pp_cover_org: 'HTX Truong Hai · Tuyen Quang',
        pp_dp_title: '📋 USER INFORMATION',
        pp_name_ph: 'Enter your name...', pp_save: 'Save',
        pp_dp_issued: 'Issued by', pp_dp_created: 'Created', pp_dp_stamps: 'Basic Stamps',
        pp_progress_done: '🎉 All stamps collected!', pp_progress_pct: '% basic journey',
        pp_cert_spec: 'Special Certificates',
        pp_no_name_hint: '💡 Enter your name on the left to earn your first stamp 🌸',
        pp_tab_basic: 'Basic Stamps',
        pp_basic_title: '🎖️ Basic Stamp Collection',
        pp_howto_title: 'How to earn stamps',
        pp_cert_title_basic: '🏆 Experience Certificate',
        pp_cert_no_stamps: 'Earn at least 1 stamp to download your certificate.',
        pp_cert_has: 'You have {n} stamps. Download as PNG.',
        pp_cert_dl: 'Download PNG',
        pp_ct_need: 'Need {min}/{total} locations to earn the certificate',
        pp_ct_enough: '🎉 Eligible for certificate!',
        pp_ct_more: '{n} more stamps needed.',
        pp_ct_cert_ready: 'Export your certificate as a PNG image.',
        pp_ct_cert_locked: 'Need {n} more locations.',
        pp_ct_name_req: 'Enter name first',
        pp_ct_downloaded: '✅ Downloaded!', pp_ct_dl: 'Download PNG',
        pp_ct_claim: 'I was here! ✓',
        pp_rev_title: '📝 Review Your Experience',
        pp_rev_rating_label: 'Your rating',
        pp_rev_loc_ph: 'Location / activity you experienced...',
        pp_rev_comment_ph: 'Share your thoughts about the Ha Giang experience...',
        pp_rev_submit: 'Submit Review',
        pp_rev_sent: '✅ Thank you! Your review has been saved.',

        // ── WomenSupportPage
        ws_hero_title: '💜 Women & Community Support',
        ws_hero_sub: 'No one has to face it alone — We are here to listen and support',
        ws_emergency_label: 'Emergency Hotlines — Free 24/7:',
        ws_our_services: 'Our Support Services',
        ws_what_help: 'How we can help',
        ws_urgent_badge: 'Urgent — Call 1800 599 920 now',
        ws_contact_btn: 'Contact Support',
        ws_modal_confidential: 'Your information is completely confidential',
        ws_urgent_banner_pre: '🆘 Emergency? Call now',
        ws_urgent_banner_post: '(free, 24/7)',
        ws_anonymous: '🎭 Contact anonymously',
        ws_name_ph: 'Your name',
        ws_phone_ph: 'Phone number (so we can call back)',
        ws_msg_ph: 'Describe your situation… (completely confidential)',
        ws_send_btn: 'Send Support Request',
        ws_sent_title: 'Message sent successfully',
        ws_sent_sub: 'HTX Truong Hai support team will contact you within 2–4 hours.',
        ws_sent_urgent: '🆘 If urgent: call 1800 599 920 now (free)',
        ws_close: 'Close',
        ws_radio_title: 'Community Radio',
        ws_radio_sub: 'A warm space to share life stories — love, family, and resilience.',
        ws_schedule_tab: '📅 Schedule',
        ws_listen_tab: 'Listen Live',
        ws_radio_tagline: 'On air every evening — Listen & Connect',
        ws_on_air: 'On Air:',
        ws_off_air: '📅 View Schedule',
        ws_play_hint: 'Tap the button ↓ to listen',
        ws_stream_hint: '💡 Broadcast follows schedule. Check the Schedule tab if no signal.',
    },
}

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('vi')

    const t = (key) => translations[lang]?.[key] ?? translations.vi[key] ?? key
    const toggleLang = () => setLang(l => (l === 'vi' ? 'en' : 'vi'))

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLang = () => useContext(LanguageContext)
